import type { UnitDef } from "../types";

export const u1: UnitDef = {
    id: "u1",
    title: "Primeiros passos",
    description: "Begrüßen, sich vorstellen, Herkunft und Zahlen",
    speaking: [
      {
        prompt: "Stell dich vor: Begrüße, sag deinen Namen, woher du kommst, wo du wohnst und wie alt du bist.",
        hints: ["Olá", "Chamo-me …", "Sou da …", "Moro em …", "Tenho … anos"],
        model: [
          { pt: "Olá, bom dia!", de: "Hallo, guten Morgen!" },
          { pt: "Chamo-me Tom.", de: "Ich heiße Tom." },
          { pt: "Sou da Alemanha, mas moro em Lisboa.", de: "Ich komme aus Deutschland, aber ich wohne in Lissabon." },
          { pt: "Tenho vinte anos. Muito prazer!", de: "Ich bin zwanzig Jahre alt. Sehr erfreut!" },
        ],
      },
      {
        prompt: "Du lernst jemanden kennen. Frag nach Name, Herkunft, Wohnort und Alter.",
        hints: ["Como …?", "De onde …?", "Onde …?", "Quantos anos …?"],
        model: [
          { pt: "Como te chamas?", de: "Wie heißt du?" },
          { pt: "De onde és?", de: "Woher kommst du?" },
          { pt: "Onde moras?", de: "Wo wohnst du?" },
          { pt: "Quantos anos tens?", de: "Wie alt bist du?" },
        ],
      },
    ],
    lessons: [
      {
        id: "ola",
        title: "Olá!",
        subtitle: "Begrüßung und Höflichkeit",
        grammar: {
          title: "Obrigado oder obrigada?",
          body: [
            "„Danke“ richtet sich nach der Person, die spricht: Männer sagen obrigado, Frauen sagen obrigada.",
            "Bom dia sagt man bis etwa 12 Uhr, danach boa tarde. Ab der Dunkelheit heißt es boa noite – das gilt für Begrüßung und Abschied.",
            "Aussprache: Unbetonte e am Wortende werden in Portugal fast verschluckt. „Boa noite“ klingt eher wie „boa noit’“.",
          ],
          examples: [
            { pt: "Obrigado!", de: "Danke! (Mann)" },
            { pt: "Obrigada!", de: "Danke! (Frau)" },
            { pt: "Boa noite!", de: "Guten Abend! / Gute Nacht!" },
          ],
        },
        words: [
          ["olá", "hallo"],
          ["bom dia", "guten Morgen"],
          ["boa tarde", "guten Tag", "ab Mittag"],
          ["boa noite", "guten Abend"],
          ["adeus", "auf Wiedersehen"],
          ["até logo", "bis später"],
          ["obrigado", "danke", "wenn ein Mann spricht"],
          ["obrigada", "danke", "wenn eine Frau spricht"],
          ["por favor", "bitte"],
          ["sim", "ja"],
          ["não", "nein"],
          ["desculpe", "Entschuldigung", "wörtlich: entschuldigen Sie"],
          ["e", "und"],
          ["percebo", "ich verstehe", "von perceber"],
          ["de nada", "gern geschehen", "Antwort auf obrigado"],
        ],
        sentences: [
          ["Olá, bom dia!", "Hallo, guten Morgen!"],
          ["Boa noite e obrigado.", "Guten Abend und danke."],
          ["Sim, por favor.", "Ja, bitte."],
          ["Não, obrigada.", "Nein, danke."],
          ["Até logo!", "Bis später!"],
          ["Desculpe, não percebo.", "Entschuldigung, ich verstehe nicht."],
        ],
        sound: {
          title: "Das stumme e am Wortende",
          body: [
            "Unbetontes e am Wortende wird in Portugal kaum gesprochen: noite klingt wie „noit“, desculpe wie „dschkulp“.",
            "Das ist einer der auffälligsten Unterschiede zum brasilianischen Portugiesisch, wo man „noitschi“ sagt.",
          ],
          examples: [
            { pt: "Boa noite!", de: "Guten Abend!" },
            { pt: "Desculpe.", de: "Entschuldigung." },
          ],
        },
        dialogue: {
          situation: "Deine Nachbarin hält dir morgens die Tür auf.",
          partner: "Dona Rosa",
          lines: [
            ["a", "Bom dia!", "Guten Morgen!"],
            ["b", "Bom dia! Obrigado.", "Guten Morgen! Danke.", ["Bom dia! Obrigada.", "Bom dia, obrigado.", "Bom dia, obrigada."]],
            ["a", "De nada.", "Gern geschehen."],
            ["b", "Até logo!", "Bis später!", ["Adeus!"]],
            ["a", "Até logo!", "Bis später!"],
          ],
          question: { q: "Was antwortet Dona Rosa auf dein Danke?", options: ["Gern geschehen", "Guten Abend", "Entschuldigung"] },
        },
      },
      {
        id: "quem-es",
        title: "Quem és tu?",
        subtitle: "Sich vorstellen mit ser",
        grammar: {
          title: "Das Verb ser (sein)",
          body: [
            "Ser beschreibt, wer oder was jemand ist: Name, Herkunft, Beruf, Eigenschaften.",
            "eu sou · tu és · ele/ela é · nós somos · eles/elas são",
            "Das Subjektpronomen kann man weglassen, die Verbform zeigt die Person: „Sou alemão“ reicht.",
            "„Ich heiße“ ist chamo-me. In Portugal steht das Pronomen im Aussagesatz hinter dem Verb, mit Bindestrich. Nach Fragewörtern rückt es davor: „Como te chamas?“",
          ],
          examples: [
            { pt: "Chamo-me Ana.", de: "Ich heiße Ana." },
            { pt: "Como te chamas?", de: "Wie heißt du?" },
            { pt: "Ela é portuguesa.", de: "Sie ist Portugiesin." },
          ],
        },
        words: [
          ["eu", "ich"],
          ["tu", "du"],
          ["ele", "er"],
          ["ela", "sie", "Singular"],
          ["sou", "ich bin"],
          ["és", "du bist"],
          ["é", "er/sie ist"],
          ["chamo-me", "ich heiße"],
          ["como", "wie"],
          ["muito prazer", "sehr erfreut"],
          ["alemão", "Deutscher"],
          ["alemã", "Deutsche"],
          ["português", "Portugiese"],
          ["portuguesa", "Portugiesin"],
          ["o", "der", "Artikel, männlich"],
          ["te chamas", "du heißt", "nach Fragewort: Como te chamas?"],
        ],
        sentences: [
          ["Como te chamas?", "Wie heißt du?"],
          ["Chamo-me Ana.", "Ich heiße Ana."],
          ["Eu sou alemão.", "Ich bin Deutscher."],
          ["Ela é portuguesa.", "Sie ist Portugiesin."],
          ["Muito prazer!", "Sehr erfreut!"],
          ["Tu és o Pedro?", "Bist du Pedro?", ["És o Pedro?"]],
        ],
        sound: {
          title: "s klingt oft wie sch",
          body: [
            "Am Wortende und vor Konsonanten spricht man s in Portugal wie „sch“: és ≈ „äsch“, português ≈ „purtugesch“.",
            "Zwischen zwei Vokalen bleibt es ein stimmhaftes s: portuguesa ≈ „purtugesa“.",
          ],
          examples: [
            { pt: "Tu és alemão?", de: "Bist du Deutscher?" },
            { pt: "Ela é portuguesa.", de: "Sie ist Portugiesin." },
          ],
        },
        dialogue: {
          situation: "Auf einer Party in Lissabon lernst du jemanden kennen.",
          partner: "Inês",
          lines: [
            ["a", "Olá! Como te chamas?", "Hallo! Wie heißt du?"],
            ["b", "Chamo-me Tom. E tu?", "Ich heiße Tom. Und du?", ["Eu chamo-me Tom. E tu?"]],
            ["a", "Chamo-me Inês. És alemão?", "Ich heiße Inês. Bist du Deutscher?"],
            ["b", "Sim, sou alemão. E tu és portuguesa?", "Ja, ich bin Deutscher. Und bist du Portugiesin?", ["Sim, sou alemão. És portuguesa?", "Sim, eu sou alemão. E tu és portuguesa?"]],
            ["a", "Sou, sim. Muito prazer!", "Ja, bin ich. Sehr erfreut!"],
            ["b", "Muito prazer!", "Sehr erfreut!"],
          ],
          question: { q: "Woher kommt Inês?", options: ["Aus Portugal", "Aus Deutschland", "Aus Brasilien"] },
        },
      },
      {
        id: "de-onde",
        title: "De onde és?",
        subtitle: "Herkunft und Wohnort",
        grammar: {
          title: "Verschmelzungen: da, do, na, no",
          body: [
            "Die Präpositionen de (aus, von) und em (in) verschmelzen mit dem Artikel:",
            "de + o = do · de + a = da · em + o = no · em + a = na",
            "Die meisten Länder haben einen Artikel: a Alemanha, o Brasil. Portugal und viele Städte (Lisboa) stehen ohne Artikel – aber: o Porto.",
          ],
          examples: [
            { pt: "Sou da Alemanha.", de: "Ich komme aus Deutschland." },
            { pt: "Moro em Lisboa.", de: "Ich wohne in Lissabon." },
            { pt: "Ele mora no Porto.", de: "Er wohnt in Porto." },
          ],
        },
        words: [
          ["onde", "wo"],
          ["de onde", "woher"],
          ["a Alemanha", "Deutschland"],
          ["Portugal", "Portugal"],
          ["Lisboa", "Lissabon"],
          ["moro", "ich wohne"],
          ["moras", "du wohnst"],
          ["a cidade", "die Stadt"],
          ["o país", "das Land"],
          ["bonito", "schön"],
          ["uma", "eine", "Artikel, weiblich"],
          ["em", "in"],
          ["da", "aus der / von der", "de + a"],
          ["do", "aus dem / vom", "de + o"],
          ["no", "im / in dem", "em + o"],
          ["na", "in der", "em + a"],
          ["mas", "aber"],
        ],
        sentences: [
          ["De onde és?", "Woher kommst du?"],
          ["Sou da Alemanha.", "Ich komme aus Deutschland.", ["Eu sou da Alemanha."]],
          ["Moro em Lisboa.", "Ich wohne in Lissabon.", ["Eu moro em Lisboa."]],
          ["Onde moras?", "Wo wohnst du?"],
          ["Lisboa é uma cidade bonita.", "Lissabon ist eine schöne Stadt."],
          ["Ele mora no Porto.", "Er wohnt in Porto."],
        ],
        sound: {
          title: "nh und das s in Lisboa",
          body: [
            "nh klingt wie „nj“, ähnlich wie in Champagner: Alemanha ≈ „alemanja“.",
            "Vor stimmhaften Konsonanten wie b, d, g, m wird s zu einem weichen „sch“ wie in Journal: Lisboa ≈ „lischboa“ mit weichem sch.",
          ],
          examples: [
            { pt: "Sou da Alemanha.", de: "Ich komme aus Deutschland." },
            { pt: "Moro em Lisboa.", de: "Ich wohne in Lissabon." },
          ],
        },
        dialogue: {
          situation: "Im Zug kommst du mit einer Mitreisenden ins Gespräch.",
          partner: "Sofia",
          lines: [
            ["a", "De onde és?", "Woher kommst du?"],
            ["b", "Sou da Alemanha. E tu?", "Ich komme aus Deutschland. Und du?", ["Eu sou da Alemanha. E tu?"]],
            ["a", "Sou do Porto, mas moro em Lisboa.", "Ich komme aus Porto, aber ich wohne in Lissabon."],
            ["b", "Lisboa é uma cidade bonita!", "Lissabon ist eine schöne Stadt!"],
            ["a", "É, sim. E tu, onde moras?", "Ja, das stimmt. Und du, wo wohnst du?"],
            ["b", "Moro em Berlim.", "Ich wohne in Berlin.", ["Eu moro em Berlim."]],
          ],
          question: { q: "Wo wohnt Sofia?", options: ["In Lissabon", "In Porto", "In Berlin"] },
        },
      },
      {
        id: "numeros",
        title: "Números",
        subtitle: "Zahlen von 0 bis 20 und das Alter",
        grammar: {
          title: "Zahlen mit Geschlecht und das Alter",
          body: [
            "Eins und zwei passen sich dem Nomen an: um café, uma água · dois cafés, duas águas.",
            "Das Alter drückt man mit ter (haben) aus: „Tenho vinte anos“ – wörtlich „Ich habe zwanzig Jahre“.",
          ],
          examples: [
            { pt: "Quantos anos tens?", de: "Wie alt bist du?" },
            { pt: "Tenho vinte anos.", de: "Ich bin zwanzig Jahre alt." },
          ],
        },
        words: [
          ["zero", "null"],
          ["um", "eins", "männlich; weiblich: uma"],
          ["dois", "zwei", "männlich; weiblich: duas"],
          ["três", "drei"],
          ["quatro", "vier"],
          ["cinco", "fünf"],
          ["seis", "sechs"],
          ["sete", "sieben"],
          ["oito", "acht"],
          ["nove", "neun"],
          ["dez", "zehn"],
          ["vinte", "zwanzig"],
          ["tenho", "ich habe"],
          ["os anos", "die Jahre"],
          ["quantos", "wie viele"],
          ["também", "auch"],
          ["o café", "der Kaffee"],
          ["a água", "das Wasser"],
          ["o irmão", "der Bruder", "Plural os irmãos: Geschwister"],
        ],
        sentences: [
          ["Quantos anos tens?", "Wie alt bist du?"],
          ["Tenho vinte anos.", "Ich bin zwanzig Jahre alt.", ["Eu tenho vinte anos."]],
          ["Um café e duas águas.", "Ein Kaffee und zwei Wasser."],
          ["Ela tem oito anos.", "Sie ist acht Jahre alt."],
          ["Tenho três irmãos.", "Ich habe drei Geschwister."],
        ],
        sound: {
          title: "Unbetontes o klingt wie u",
          body: [
            "Ein unbetontes o, besonders am Wortende, klingt in Portugal wie „u“: quatro ≈ „kwatru“, cinco ≈ „ßinku“, oito ≈ „oitu“.",
            "Betontes o bleibt o: dois, nove.",
          ],
          examples: [
            { pt: "quatro, cinco, oito", de: "vier, fünf, acht" },
            { pt: "Tenho vinte anos.", de: "Ich bin zwanzig Jahre alt." },
          ],
        },
        dialogue: {
          situation: "Beim Sprachtandem stellt ihr euch gegenseitig Fragen.",
          partner: "Marta",
          lines: [
            ["a", "Quantos anos tens?", "Wie alt bist du?"],
            ["b", "Tenho vinte anos. E tu?", "Ich bin zwanzig Jahre alt. Und du?", ["Eu tenho vinte anos. E tu?"]],
            ["a", "Eu também tenho vinte!", "Ich bin auch zwanzig!"],
            ["b", "Tens irmãos?", "Hast du Geschwister?", ["Tu tens irmãos?"]],
            ["a", "Tenho dois irmãos e uma irmã.", "Ich habe zwei Brüder und eine Schwester."],
          ],
          question: { q: "Wie viele Geschwister hat Marta?", options: ["Drei", "Zwei", "Eins"] },
        },
      },
    ],
};
