import type { UnitDef } from "../types";

export const u2: UnitDef = {
    id: "u2",
    title: "O dia a dia",
    description: "Café, Essen, Familie und Befinden",
    speaking: [
      {
        prompt: "Bestell im Café ein Getränk und etwas zu essen. Dann bitte um die Rechnung.",
        hints: ["Queria …", "se faz favor", "A conta …"],
        model: [
          { pt: "Bom dia! Queria um galão e um pastel de nata, se faz favor.", de: "Guten Morgen! Ich hätte gern einen Milchkaffee und ein Puddingtörtchen, bitte." },
          { pt: "A conta, se faz favor.", de: "Die Rechnung, bitte." },
          { pt: "Obrigado!", de: "Danke!" },
        ],
      },
      {
        prompt: "Erzähl, was du gern isst und trinkst – und was nicht.",
        hints: ["Gosto de …", "Não gosto de …", "Bebo …", "ao jantar"],
        model: [
          { pt: "Gosto muito de peixe.", de: "Ich mag Fisch sehr." },
          { pt: "Não gosto de carne.", de: "Ich mag kein Fleisch." },
          { pt: "Ao jantar bebo vinho ou água.", de: "Zum Abendessen trinke ich Wein oder Wasser." },
        ],
      },
      {
        prompt: "Stell deine Familie vor: Wer gehört dazu, wie heißen sie, wo wohnen sie?",
        hints: ["o meu pai", "a minha mãe", "Tenho …", "chama-se", "moram em"],
        model: [
          { pt: "Tenho uma irmã e um irmão.", de: "Ich habe eine Schwester und einen Bruder." },
          { pt: "A minha mãe chama-se Ana e o meu pai chama-se João.", de: "Meine Mutter heißt Ana und mein Vater heißt João." },
          { pt: "Os meus pais moram em Hamburgo.", de: "Meine Eltern wohnen in Hamburg." },
        ],
      },
    ],
    lessons: [
      {
        id: "cafe",
        title: "No café",
        subtitle: "Bestellen wie in Lissabon",
        grammar: {
          title: "Höflich bestellen",
          body: [
            "Queria („ich wollte“) ist die übliche höfliche Form zum Bestellen – wie das deutsche „Ich hätte gern“.",
            "Se faz favor ist typisch für Portugal: zum Bitten und um die Bedienung zu rufen. Por favor geht auch.",
            "Uma bica ist in Lissabon ein Espresso, ein galão ein Milchkaffee im Glas.",
          ],
          examples: [
            { pt: "Queria uma bica, se faz favor.", de: "Ich hätte gern einen Espresso, bitte." },
            { pt: "A conta, se faz favor.", de: "Die Rechnung, bitte." },
          ],
        },
        words: [
          ["o café", "der Kaffee"],
          ["a bica", "der Espresso", "Lissabon"],
          ["o galão", "der Milchkaffee"],
          ["a água", "das Wasser"],
          ["o sumo", "der Saft"],
          ["a laranja", "die Orange"],
          ["o pão", "das Brot"],
          ["o pastel de nata", "das Puddingtörtchen"],
          ["queria", "ich hätte gern"],
          ["se faz favor", "bitte"],
          ["a conta", "die Rechnung"],
          ["com", "mit"],
          ["sem", "ohne"],
          ["o açúcar", "der Zucker"],
          ["o gás", "das Gas, die Kohlensäure", "com gás = mit Kohlensäure"],
          ["que", "was (in „o que“)", "o que = was"],
          ["desejar", "wünschen", "O que deseja? = Was darf es sein?"],
          ["mais", "mehr, noch"],
          ["alguma coisa", "etwas"],
          ["muito bem", "sehr gut, in Ordnung"],
        ],
        sentences: [
          ["Queria uma bica, se faz favor.", "Ich hätte gern einen Espresso, bitte.", ["Queria uma bica, por favor."]],
          ["Um galão e um pastel de nata.", "Ein Milchkaffee und ein Puddingtörtchen."],
          ["A conta, se faz favor.", "Die Rechnung, bitte.", ["A conta, por favor."]],
          ["Um café sem açúcar.", "Ein Kaffee ohne Zucker."],
          ["Queria um sumo de laranja.", "Ich hätte gern einen Orangensaft."],
          ["Uma água com gás, se faz favor.", "Ein Wasser mit Kohlensäure, bitte.", ["Uma água com gás, por favor."]],
        ],
        sound: {
          title: "Die Nasale ão und ã",
          body: [
            "ão ist ein nasaler Doppellaut – wie „au“, durch die Nase gesprochen, ohne ein n am Ende: pão, galão, não.",
            "ã allein klingt wie ein nasales, dumpfes a: maçã, irmã.",
          ],
          examples: [
            { pt: "Um galão e um pão.", de: "Ein Milchkaffee und ein Brot." },
            { pt: "Não, obrigado.", de: "Nein, danke." },
          ],
        },
        dialogue: {
          situation: "Du bestellst in einer pastelaria in Lissabon.",
          partner: "Empregado",
          lines: [
            ["a", "Bom dia! O que deseja?", "Guten Morgen! Was darf es sein?"],
            ["b", "Queria uma bica, se faz favor.", "Ich hätte gern einen Espresso, bitte.", ["Queria uma bica, por favor."]],
            ["a", "Com açúcar?", "Mit Zucker?"],
            ["b", "Não, sem açúcar. E um pastel de nata.", "Nein, ohne Zucker. Und ein Puddingtörtchen.", ["Não, sem açúcar, e um pastel de nata."]],
            ["a", "Muito bem. Mais alguma coisa?", "Sehr gut. Sonst noch etwas?"],
            ["b", "Não, obrigado. A conta, se faz favor.", "Nein, danke. Die Rechnung, bitte.", ["Não, obrigada. A conta, se faz favor.", "Não, obrigado. A conta, por favor.", "Não, obrigada. A conta, por favor."]],
          ],
          question: { q: "Was bestellst du?", options: ["Einen Espresso ohne Zucker und ein Puddingtörtchen", "Einen Milchkaffee mit Zucker", "Einen Orangensaft und ein Brot"] },
        },
      },
      {
        id: "comer",
        title: "Comer e beber",
        subtitle: "Essen, Trinken, Vorlieben",
        grammar: {
          title: "Verben auf -er und gostar de",
          body: [
            "Regelmäßige Verben auf -er, z. B. comer (essen): eu como · tu comes · ele/ela come · nós comemos · eles comem",
            "Gostar (mögen) braucht immer de: gosto de peixe. Mit Artikel verschmilzt es: gosto do vinho, gosto da praia.",
            "Verneinung: não steht direkt vor dem Verb – „Não gosto de cerveja“.",
          ],
          examples: [
            { pt: "Eu gosto de peixe.", de: "Ich mag Fisch." },
            { pt: "Não gosto de cerveja.", de: "Ich mag kein Bier." },
          ],
        },
        words: [
          ["comer", "essen"],
          ["beber", "trinken"],
          ["gosto de", "ich mag"],
          ["o peixe", "der Fisch"],
          ["a carne", "das Fleisch"],
          ["o vinho", "der Wein"],
          ["a cerveja", "das Bier"],
          ["o pequeno-almoço", "das Frühstück"],
          ["o almoço", "das Mittagessen"],
          ["o jantar", "das Abendessen"],
          ["muito", "sehr, viel"],
          ["ao", "zu / am / im", "a + o, z. B. ao jantar = zum Abendessen"],
          ["às", "um (bei Uhrzeiten)", "a + as, z. B. às oito = um acht"],
          ["ou", "oder"],
          ["hoje", "heute"],
        ],
        sentences: [
          ["Eu gosto de peixe.", "Ich mag Fisch.", ["Gosto de peixe."]],
          ["Tu bebes vinho?", "Trinkst du Wein?", ["Bebes vinho?"]],
          ["Ela come carne.", "Sie isst Fleisch."],
          ["Não gosto de cerveja.", "Ich mag kein Bier.", ["Eu não gosto de cerveja."]],
          ["O jantar é às oito.", "Das Abendessen ist um acht."],
          ["Bebo café ao pequeno-almoço.", "Ich trinke Kaffee zum Frühstück.", ["Eu bebo café ao pequeno-almoço."]],
        ],
        sound: {
          title: "x und ei",
          body: [
            "x klingt am Wortanfang und nach ei meist wie „sch“: peixe ≈ „päisch“.",
            "ei spricht man in Lissabon fast wie „äi“ mit dunklem a: peixe, queijo.",
          ],
          examples: [
            { pt: "Gosto de peixe.", de: "Ich mag Fisch." },
            { pt: "o peixe", de: "der Fisch" },
          ],
        },
        dialogue: {
          situation: "Ihr plant ein Abendessen und sprecht über Vorlieben.",
          partner: "Rui",
          lines: [
            ["a", "Gostas de peixe?", "Magst du Fisch?"],
            ["b", "Gosto muito! E tu?", "Sehr! Und du?", ["Sim, gosto muito! E tu?", "Gosto muito. E tu?"]],
            ["a", "Eu não gosto de peixe. Gosto de carne.", "Ich mag keinen Fisch. Ich mag Fleisch."],
            ["b", "Bebes vinho ao jantar?", "Trinkst du Wein zum Abendessen?", ["Tu bebes vinho ao jantar?"]],
            ["a", "Hoje não. Bebo água.", "Heute nicht. Ich trinke Wasser."],
          ],
          question: { q: "Was mag Rui?", options: ["Fleisch", "Fisch", "Bier"] },
        },
      },
      {
        id: "familia",
        title: "A família",
        subtitle: "Familie und Possessivpronomen",
        grammar: {
          title: "Mein, dein – mit Artikel",
          body: [
            "In Portugal steht vor dem Possessivpronomen normalerweise der Artikel: o meu pai, a minha mãe.",
            "o meu / a minha (mein) · o teu / a tua (dein) · os meus / as minhas (meine, Plural)",
            "Os irmãos kann „die Brüder“ oder „die Geschwister“ bedeuten, os pais sind „die Eltern“.",
          ],
          examples: [
            { pt: "Esta é a minha mãe.", de: "Das ist meine Mutter." },
            { pt: "Os meus pais moram em Faro.", de: "Meine Eltern wohnen in Faro." },
          ],
        },
        words: [
          ["o pai", "der Vater"],
          ["a mãe", "die Mutter"],
          ["os pais", "die Eltern"],
          ["o irmão", "der Bruder"],
          ["a irmã", "die Schwester"],
          ["os irmãos", "die Geschwister"],
          ["o filho", "der Sohn"],
          ["a filha", "die Tochter"],
          ["o meu", "mein"],
          ["a minha", "meine"],
          ["esta", "diese, das (hier)", "weiblich; männlich: este"],
          ["este", "dieser, das (hier)", "männlich"],
          ["chamar-se", "heißen", "chama-se = er/sie heißt"],
          ["morar", "wohnen", "moram = sie wohnen"],
          ["ter", "haben", "tenho, tens, tem"],
          ["quem", "wer"],
        ],
        sentences: [
          ["Esta é a minha mãe.", "Das ist meine Mutter."],
          ["Tenho uma irmã.", "Ich habe eine Schwester.", ["Eu tenho uma irmã."]],
          ["O meu pai chama-se João.", "Mein Vater heißt João."],
          ["Os meus pais moram em Faro.", "Meine Eltern wohnen in Faro."],
          ["Tens irmãos?", "Hast du Geschwister?", ["Tu tens irmãos?"]],
          ["A minha filha tem dez anos.", "Meine Tochter ist zehn Jahre alt."],
        ],
        sound: {
          title: "lh und ãe",
          body: [
            "lh klingt wie „lj“, ähnlich wie in Brillant: filho ≈ „filju“, filha ≈ „filja“.",
            "ãe in mãe ist ein nasales „äi“ – ungefähr „mãi“ durch die Nase.",
          ],
          examples: [
            { pt: "o meu filho", de: "mein Sohn" },
            { pt: "a minha mãe", de: "meine Mutter" },
          ],
        },
        dialogue: {
          situation: "Eine Freundin schaut sich deine Fotos an.",
          partner: "Catarina",
          lines: [
            ["a", "Quem é esta?", "Wer ist das?"],
            ["b", "Esta é a minha mãe.", "Das ist meine Mutter.", ["É a minha mãe."]],
            ["a", "E este?", "Und der hier?"],
            ["b", "É o meu pai. Chama-se João.", "Das ist mein Vater. Er heißt João.", ["É o meu pai, chama-se João.", "Este é o meu pai. Chama-se João."]],
            ["a", "Tens irmãos?", "Hast du Geschwister?"],
            ["b", "Tenho uma irmã.", "Ich habe eine Schwester.", ["Eu tenho uma irmã."]],
          ],
          question: { q: "Wie heißt dein Vater?", options: ["João", "Pedro", "Rui"] },
        },
      },
      {
        id: "estar",
        title: "Ser ou estar?",
        subtitle: "Befinden, Zustand, Ort",
        grammar: {
          title: "Estar und die Verlaufsform",
          body: [
            "Estar (sein) beschreibt Vorübergehendes: Befinden, Stimmung, Aufenthaltsort. Ser beschreibt, was dauerhaft ist.",
            "eu estou · tu estás · ele/ela está · nós estamos · eles estão",
            "„Gerade etwas tun“ heißt in Portugal estar a + Infinitiv: „Estou a trabalhar“. Die brasilianische Form „estou trabalhando“ klingt hier fremd.",
          ],
          examples: [
            { pt: "Como estás?", de: "Wie geht es dir?" },
            { pt: "Estou a trabalhar.", de: "Ich arbeite gerade." },
          ],
        },
        words: [
          ["estou", "ich bin (Zustand)"],
          ["estás", "du bist (Zustand)"],
          ["está", "er/sie ist (Zustand)"],
          ["bem", "gut"],
          ["mal", "schlecht"],
          ["cansado", "müde"],
          ["contente", "froh"],
          ["hoje", "heute"],
          ["aqui", "hier"],
          ["em casa", "zu Hause"],
          ["trabalhar", "arbeiten"],
        ],
        sentences: [
          ["Como estás?", "Wie geht es dir?"],
          ["Estou bem, obrigado.", "Mir geht es gut, danke.", ["Eu estou bem, obrigado.", "Estou bem, obrigada."]],
          ["Hoje estou cansada.", "Heute bin ich müde.", ["Hoje estou cansado."]],
          ["Ela está em casa.", "Sie ist zu Hause."],
          ["Estou a trabalhar.", "Ich arbeite gerade.", ["Eu estou a trabalhar."]],
          ["O Pedro está aqui?", "Ist Pedro hier?"],
        ],
        sound: {
          title: "es- am Wortanfang",
          body: [
            "Unbetontes e am Wortanfang verschwindet fast, und s davor klingt wie „sch“: estou ≈ „schtô“, estás ≈ „schtasch“.",
            "So klingt ein ganzer Satz schnell ganz anders als geschrieben – hör genau hin.",
          ],
          examples: [
            { pt: "Estou bem.", de: "Mir geht es gut." },
            { pt: "Como estás?", de: "Wie geht es dir?" },
          ],
        },
        dialogue: {
          situation: "Du triffst eine Kollegin im Flur.",
          partner: "Joana",
          lines: [
            ["a", "Olá! Como estás?", "Hallo! Wie geht es dir?"],
            ["b", "Estou bem, obrigado. E tu?", "Mir geht es gut, danke. Und dir?", ["Estou bem, obrigada. E tu?", "Bem, obrigado. E tu?", "Bem, obrigada. E tu?"]],
            ["a", "Estou cansada. Estou a trabalhar muito.", "Ich bin müde. Ich arbeite gerade viel."],
            ["b", "O Pedro está aqui?", "Ist Pedro hier?"],
            ["a", "Não, hoje está em casa.", "Nein, heute ist er zu Hause."],
          ],
          question: { q: "Warum ist Joana müde?", options: ["Sie arbeitet gerade viel", "Sie ist krank", "Sie war am Strand"] },
        },
      },
    ],
};
