import type { UnitDef } from "../types";

export const u3: UnitDef = {
    id: "u3",
    title: "Na cidade",
    description: "Wege, Verkehrsmittel, Einkaufen und Zeit",
    speaking: [
      {
        prompt: "Du suchst den Bahnhof. Sprich jemanden höflich an, frag nach dem Weg und ob es weit ist. Bedank dich.",
        hints: ["Desculpe", "Onde fica …?", "longe", "Obrigado/a"],
        model: [
          { pt: "Desculpe, onde fica a estação?", de: "Entschuldigung, wo ist der Bahnhof?" },
          { pt: "Fica longe?", de: "Ist es weit?" },
          { pt: "Obrigado!", de: "Danke!" },
        ],
      },
      {
        prompt: "Auf dem Markt: Kauf ein Kilo Äpfel, frag nach dem Preis und ob du mit Karte zahlen kannst.",
        hints: ["Queria …", "Quanto custa?", "Posso …?"],
        model: [
          { pt: "Bom dia! Queria um quilo de maçãs.", de: "Guten Morgen! Ich hätte gern ein Kilo Äpfel." },
          { pt: "Quanto custa?", de: "Was kostet das?" },
          { pt: "Posso pagar com cartão?", de: "Kann ich mit Karte bezahlen?" },
        ],
      },
      {
        prompt: "Erzähl von deiner Woche: An welchen Tagen arbeitest du, und was machst du am Wochenende?",
        hints: ["de segunda a sexta", "ao sábado", "ao domingo", "vou …"],
        model: [
          { pt: "De segunda a sexta trabalho.", de: "Von Montag bis Freitag arbeite ich." },
          { pt: "Ao sábado vou ao mercado.", de: "Samstags gehe ich auf den Markt." },
          { pt: "Ao domingo vou à praia.", de: "Sonntags gehe ich an den Strand." },
        ],
      },
    ],
    lessons: [
      {
        id: "onde-fica",
        title: "Onde fica?",
        subtitle: "Nach dem Weg fragen",
        grammar: {
          title: "Ficar für Orte",
          body: [
            "Für die Lage von Orten sagt man in Portugal gern ficar: „Onde fica a estação?“ – Wo ist der Bahnhof?",
            "Richtungen: à esquerda (links), à direita (rechts), em frente (geradeaus).",
            "Desculpe ist die höfliche Art, jemanden anzusprechen.",
          ],
          examples: [
            { pt: "Onde fica a estação?", de: "Wo ist der Bahnhof?" },
            { pt: "É ali, à direita.", de: "Es ist dort, rechts." },
          ],
        },
        words: [
          ["onde fica", "wo ist"],
          ["a rua", "die Straße"],
          ["a estação", "der Bahnhof"],
          ["a praia", "der Strand"],
          ["o museu", "das Museum"],
          ["a casa de banho", "die Toilette"],
          ["perto", "nah"],
          ["longe", "weit weg"],
          ["à esquerda", "links"],
          ["à direita", "rechts"],
          ["em frente", "geradeaus"],
          ["ali", "dort"],
          ["siga", "gehen Sie (weiter)", "Imperativ von seguir"],
          ["depois", "dann, danach"],
        ],
        sentences: [
          ["Onde fica a estação?", "Wo ist der Bahnhof?"],
          ["Desculpe, onde fica a casa de banho?", "Entschuldigung, wo ist die Toilette?"],
          ["É ali, à direita.", "Es ist dort, rechts."],
          ["A praia fica perto.", "Der Strand ist nah."],
          ["Siga em frente.", "Gehen Sie geradeaus."],
          ["O museu fica longe?", "Ist das Museum weit weg?"],
        ],
        sound: {
          title: "Zwei verschiedene r",
          body: [
            "Am Wortanfang und bei rr klingt r wie das deutsche Rachen-r: rua, carro.",
            "Ein einzelnes r zwischen Vokalen ist ein kurz getipptes Zungen-r: direita, para.",
          ],
          examples: [
            { pt: "a rua", de: "die Straße" },
            { pt: "à direita", de: "rechts" },
          ],
        },
        dialogue: {
          situation: "Du suchst in einer fremden Stadt den Bahnhof.",
          partner: "Senhor Alves",
          lines: [
            ["b", "Desculpe, onde fica a estação?", "Entschuldigung, wo ist der Bahnhof?", ["Desculpe, onde é a estação?"]],
            ["a", "A estação? Fica perto. Siga em frente e depois à direita.", "Der Bahnhof? Er ist in der Nähe. Gehen Sie geradeaus und dann rechts."],
            ["b", "Em frente e à direita. Obrigado!", "Geradeaus und rechts. Danke!", ["Em frente e à direita. Obrigada!"]],
            ["a", "De nada!", "Gern geschehen!"],
          ],
          question: { q: "Wie kommst du zum Bahnhof?", options: ["Geradeaus, dann rechts", "Links, dann geradeaus", "Mit dem Bus"] },
        },
      },
      {
        id: "transportes",
        title: "Transportes",
        subtitle: "Zug, Bus und Straßenbahn",
        grammar: {
          title: "Ir und apanhar",
          body: [
            "Ir (gehen, fahren): eu vou · tu vais · ele/ela vai · nós vamos · eles vão",
            "Ein Verkehrsmittel „nehmen“ heißt in Portugal apanhar: apanhar o autocarro. Das brasilianische „pegar“ solltest du hier vermeiden.",
            "Einige Wörter sind typisch europäisch: o comboio (Zug), o autocarro (Bus), o elétrico (Straßenbahn).",
          ],
          examples: [
            { pt: "Vou apanhar o autocarro.", de: "Ich nehme den Bus." },
            { pt: "Vou a pé.", de: "Ich gehe zu Fuß." },
          ],
        },
        words: [
          ["o comboio", "der Zug"],
          ["o autocarro", "der Bus"],
          ["o elétrico", "die Straßenbahn"],
          ["o metro", "die U-Bahn"],
          ["o bilhete", "die Fahrkarte"],
          ["a paragem", "die Haltestelle"],
          ["apanhar", "nehmen (Verkehrsmittel)"],
          ["vou", "ich gehe, ich fahre"],
          ["para", "nach, zu"],
          ["a pé", "zu Fuß"],
          ["quando", "wann"],
          ["partir", "abfahren, abreisen", "„parte“ = er/sie/es fährt ab"],
          ["o euro", "der Euro"],
        ],
        sentences: [
          ["Vou apanhar o autocarro.", "Ich nehme den Bus.", ["Eu vou apanhar o autocarro."]],
          ["Onde fica a paragem?", "Wo ist die Haltestelle?"],
          ["Um bilhete para o Porto, se faz favor.", "Eine Fahrkarte nach Porto, bitte.", ["Um bilhete para o Porto, por favor."]],
          ["Quando parte o comboio?", "Wann fährt der Zug ab?"],
          ["Vou a pé.", "Ich gehe zu Fuß.", ["Eu vou a pé."]],
          ["Apanho o elétrico.", "Ich nehme die Straßenbahn.", ["Eu apanho o elétrico."]],
        ],
        sound: {
          title: "-agem und -em am Wortende",
          body: [
            "Endungen auf -em klingen nasal wie „ãi“: sem, bem, a paragem ≈ „paRAschãi“.",
            "Das g vor e klingt wie das weiche sch in Journal.",
          ],
          examples: [
            { pt: "a paragem", de: "die Haltestelle" },
            { pt: "Vou a pé.", de: "Ich gehe zu Fuß." },
          ],
        },
        dialogue: {
          situation: "Am Fahrkartenschalter in Lissabon.",
          partner: "Funcionária",
          lines: [
            ["b", "Um bilhete para o Porto, se faz favor.", "Eine Fahrkarte nach Porto, bitte.", ["Um bilhete para o Porto, por favor."]],
            ["a", "Aqui está. São vinte euros.", "Bitte schön. Das macht zwanzig Euro."],
            ["b", "Quando parte o comboio?", "Wann fährt der Zug ab?"],
            ["a", "Parte às dez.", "Er fährt um zehn ab."],
            ["b", "Obrigado. E onde fica a paragem do autocarro?", "Danke. Und wo ist die Bushaltestelle?", ["Obrigada. E onde fica a paragem do autocarro?", "Onde fica a paragem do autocarro?"]],
            ["a", "Ali, à esquerda.", "Dort, links."],
          ],
          question: { q: "Wann fährt der Zug ab?", options: ["Um zehn", "Um acht", "Um zwanzig nach zehn"] },
        },
      },
      {
        id: "compras",
        title: "Às compras",
        subtitle: "Einkaufen und bezahlen",
        grammar: {
          title: "Preise und Mengen",
          body: [
            "Nach dem Preis fragt man mit „Quanto custa?“ (Was kostet das?), bei mehreren Dingen „Quanto custam?“.",
            "Mengenangaben mit de: um quilo de maçãs, uma garrafa de água.",
            "Posso …? (Kann ich …?) + Infinitiv: „Posso pagar com cartão?“",
          ],
          examples: [
            { pt: "Quanto custa?", de: "Was kostet das?" },
            { pt: "São cinco euros.", de: "Das macht fünf Euro." },
          ],
        },
        words: [
          ["quanto custa", "was kostet"],
          ["caro", "teuer"],
          ["barato", "billig"],
          ["o mercado", "der Markt"],
          ["a loja", "das Geschäft"],
          ["a fruta", "das Obst"],
          ["a maçã", "der Apfel"],
          ["o quilo", "das Kilo"],
          ["pagar", "bezahlen"],
          ["o cartão", "die Karte", "hier: Bank-/Kreditkarte"],
          ["o dinheiro", "das Geld"],
          ["posso", "ich kann, darf ich"],
          ["o que", "was"],
        ],
        sentences: [
          ["Quanto custa?", "Was kostet das?"],
          ["É muito caro.", "Das ist sehr teuer."],
          ["Queria um quilo de maçãs.", "Ich hätte gern ein Kilo Äpfel."],
          ["Posso pagar com cartão?", "Kann ich mit Karte bezahlen?"],
          ["São cinco euros.", "Das macht fünf Euro."],
          ["Mais alguma coisa?", "Sonst noch etwas?"],
        ],
        sound: {
          title: "ç und c",
          body: [
            "ç klingt immer wie scharfes s: maçã ≈ „maßã“, açúcar ≈ „aßukar“.",
            "c vor e und i ist ebenfalls ein s, sonst ein k: cidade, aber cartão.",
          ],
          examples: [
            { pt: "Queria um quilo de maçãs.", de: "Ich hätte gern ein Kilo Äpfel." },
            { pt: "com cartão", de: "mit Karte" },
          ],
        },
        dialogue: {
          situation: "Am Obststand auf dem Markt.",
          partner: "Dona Fátima",
          lines: [
            ["a", "Bom dia! O que deseja?", "Guten Morgen! Was darf es sein?"],
            ["b", "Queria um quilo de maçãs.", "Ich hätte gern ein Kilo Äpfel.", ["Queria um quilo de maçãs, se faz favor.", "Queria um quilo de maçãs, por favor."]],
            ["a", "Mais alguma coisa?", "Sonst noch etwas?"],
            ["b", "Não, obrigado. Quanto custa?", "Nein, danke. Was kostet das?", ["Não, obrigada. Quanto custa?", "Não, obrigado. Quanto é?", "Não, obrigada. Quanto é?"]],
            ["a", "São dois euros.", "Das macht zwei Euro."],
            ["b", "Posso pagar com cartão?", "Kann ich mit Karte bezahlen?"],
            ["a", "Pode, sim.", "Ja, können Sie."],
          ],
          question: { q: "Was kosten die Äpfel?", options: ["Zwei Euro", "Fünf Euro", "Zehn Euro"] },
        },
      },
      {
        id: "horas",
        title: "As horas",
        subtitle: "Uhrzeit und Verabredungen",
        grammar: {
          title: "Wie spät ist es?",
          body: [
            "Bei einer Stunde steht é, sonst são: é uma hora · são duas horas · são três e meia.",
            "e meia heißt wörtlich „und halb“: „São três e meia“ = drei Uhr dreißig, also halb vier. e um quarto = Viertel nach, menos um quarto = Viertel vor.",
            "„Um“ bei Uhrzeiten: às – „às oito“ (um acht), aber „à uma“ (um eins).",
          ],
          examples: [
            { pt: "Que horas são?", de: "Wie spät ist es?" },
            { pt: "São três e meia.", de: "Es ist halb vier." },
          ],
        },
        words: [
          ["que horas são", "wie spät ist es"],
          ["a hora", "die Stunde, die Uhrzeit"],
          ["e meia", "und halb (= 30 Minuten nach der vollen Stunde)"],
          ["e um quarto", "Viertel nach"],
          ["menos um quarto", "Viertel vor"],
          ["o meio-dia", "der Mittag"],
          ["a meia-noite", "die Mitternacht"],
          ["agora", "jetzt"],
          ["cedo", "früh"],
          ["tarde", "spät"],
          ["às", "um (Uhrzeit)", "a + as, z. B. às oito = um acht"],
          ["abrir", "öffnen, aufmachen"],
          ["já", "schon"],
          ["chegar", "ankommen"],
          ["ainda", "noch"],
        ],
        sentences: [
          ["Que horas são?", "Wie spät ist es?"],
          ["São três e meia.", "Es ist halb vier."],
          ["É meio-dia.", "Es ist Mittag."],
          ["O museu abre às dez.", "Das Museum öffnet um zehn."],
          ["Já é tarde.", "Es ist schon spät."],
          ["Chego às oito e um quarto.", "Ich komme um Viertel nach acht an."],
        ],
        sound: {
          title: "Das stumme h",
          body: [
            "h am Wortanfang wird nie gesprochen: hora ≈ „ora“, hoje ≈ „osch“.",
            "Nur in den Verbindungen ch (sch), lh und nh verändert h den Laut davor.",
          ],
          examples: [
            { pt: "Que horas são?", de: "Wie spät ist es?" },
            { pt: "hoje", de: "heute" },
          ],
        },
        dialogue: {
          situation: "Du fragst auf der Straße nach der Uhrzeit.",
          partner: "Senhora",
          lines: [
            ["b", "Desculpe, que horas são?", "Entschuldigung, wie spät ist es?", ["Que horas são?"]],
            ["a", "São três e meia.", "Es ist halb vier."],
            ["b", "Obrigado. Já é tarde!", "Danke. Es ist schon spät!", ["Obrigada. Já é tarde!", "Obrigado, já é tarde!", "Obrigada, já é tarde!"]],
            ["a", "Tarde? Não, ainda é cedo!", "Spät? Nein, es ist noch früh!"],
          ],
          question: { q: "Wie spät ist es?", options: ["Halb vier", "Halb drei", "Viertel nach drei"] },
        },
      },
      {
        id: "semana",
        title: "A semana",
        subtitle: "Wochentage und Pläne",
        grammar: {
          title: "Wochentage auf Portugiesisch",
          body: [
            "Die Werktage werden gezählt: segunda-feira (Montag) bis sexta-feira (Freitag). Im Alltag lässt man -feira oft weg: „Até segunda!“",
            "Sábado und domingo haben eigene Namen.",
            "„Sonntags“ (regelmäßig) heißt ao domingo, „am Sonntag“ (einmalig) no domingo.",
          ],
          examples: [
            { pt: "Hoje é sexta-feira.", de: "Heute ist Freitag." },
            { pt: "Ao domingo não trabalho.", de: "Sonntags arbeite ich nicht." },
          ],
        },
        words: [
          ["segunda-feira", "Montag"],
          ["terça-feira", "Dienstag"],
          ["quarta-feira", "Mittwoch"],
          ["quinta-feira", "Donnerstag"],
          ["sexta-feira", "Freitag"],
          ["o sábado", "der Samstag"],
          ["o domingo", "der Sonntag"],
          ["a semana", "die Woche"],
          ["o fim de semana", "das Wochenende"],
          ["amanhã", "morgen"],
          ["ontem", "gestern"],
          ["então", "dann, also"],
        ],
        sentences: [
          ["Hoje é sexta-feira.", "Heute ist Freitag."],
          ["Amanhã vou à praia.", "Morgen gehe ich an den Strand."],
          ["Ao domingo não trabalho.", "Sonntags arbeite ich nicht."],
          ["Bom fim de semana!", "Schönes Wochenende!"],
          ["Até segunda!", "Bis Montag!"],
          ["Ontem foi quarta-feira.", "Gestern war Mittwoch."],
        ],
        sound: {
          title: "Fragen ohne Fragewort",
          body: [
            "Ja/Nein-Fragen sehen aus wie Aussagesätze – nur die Stimme geht am Ende nach oben: „Vais à praia?“",
            "Aussage: „Vais à praia.“ (Du gehst an den Strand.) Frage: „Vais à praia?“ (Gehst du an den Strand?)",
          ],
          examples: [
            { pt: "Vais à praia?", de: "Gehst du an den Strand?" },
            { pt: "Vou à praia.", de: "Ich gehe an den Strand." },
          ],
        },
        dialogue: {
          situation: "Ein Freund fragt nach deinem Wochenende.",
          partner: "Miguel",
          lines: [
            ["a", "Vais à praia no sábado?", "Gehst du am Samstag an den Strand?"],
            ["b", "Não, no sábado trabalho.", "Nein, am Samstag arbeite ich.", ["Não, trabalho no sábado.", "Não, no sábado eu trabalho."]],
            ["a", "E no domingo?", "Und am Sonntag?"],
            ["b", "No domingo vou à praia.", "Am Sonntag gehe ich an den Strand.", ["No domingo eu vou à praia.", "Vou à praia no domingo."]],
            ["a", "Boa! Então até domingo!", "Super! Dann bis Sonntag!"],
            ["b", "Bom fim de semana!", "Schönes Wochenende!"],
          ],
          question: { q: "Wann gehst du an den Strand?", options: ["Am Sonntag", "Am Samstag", "Am Freitag"] },
        },
      },
    ],
};
