import type { UnitDef } from "../types";

export const u4: UnitDef = {
    id: "u4",
    title: "A minha vida",
    description: "Sprachen, Beruf, Tagesablauf und Pläne",
    speaking: [
      {
        prompt: "Erzähl von deinem Beruf und welche Sprachen du sprichst.",
        hints: ["Sou …", "Trabalho num/numa …", "Falo …", "Estudo …"],
        model: [
          { pt: "Sou engenheiro e trabalho numa empresa alemã.", de: "Ich bin Ingenieur und arbeite in einer deutschen Firma." },
          { pt: "Falo alemão e inglês.", de: "Ich spreche Deutsch und Englisch." },
          { pt: "Estudo português todos os dias.", de: "Ich lerne jeden Tag Portugiesisch." },
        ],
      },
      {
        prompt: "Beschreib deinen typischen Tag – vom Aufstehen bis zum Schlafengehen.",
        hints: ["Levanto-me …", "Tomo duche …", "Saio de casa …", "À noite …", "Deito-me …"],
        model: [
          { pt: "Levanto-me às sete.", de: "Ich stehe um sieben auf." },
          { pt: "Tomo duche e saio de casa às oito.", de: "Ich dusche und gehe um acht aus dem Haus." },
          { pt: "À noite deito-me às onze.", de: "Abends gehe ich um elf ins Bett." },
        ],
      },
      {
        prompt: "Lade jemanden für heute Abend ins Kino ein und macht eine Uhrzeit aus.",
        hints: ["Queres …?", "logo à noite", "A que horas?", "Combinado"],
        model: [
          { pt: "Queres ir ao cinema logo à noite?", de: "Willst du heute Abend ins Kino gehen?" },
          { pt: "Às nove?", de: "Um neun?" },
          { pt: "Combinado, até logo!", de: "Abgemacht, bis später!" },
        ],
      },
    ],
    lessons: [
      {
        id: "falo",
        title: "Falo português",
        subtitle: "Regelmäßige Verben auf -ar",
        grammar: {
          title: "Verben auf -ar, jetzt mit wir und sie",
          body: [
            "Die meisten Verben enden auf -ar und folgen alle demselben Muster, z. B. falar (sprechen):",
            "eu falo · tu falas · ele/ela fala · nós falamos · eles/elas falam",
            "Genauso gehen estudar (lernen), trabalhar (arbeiten), morar (wohnen) und viele mehr – wer ein -ar-Verb kann, kann alle.",
            "Sprachen haben keinen Großbuchstaben: o português, o inglês, o alemão. Nach falar fällt der Artikel meist weg: „Falo português.“",
          ],
          examples: [
            { pt: "Nós estudamos português.", de: "Wir lernen Portugiesisch." },
            { pt: "Eles trabalham em Lisboa.", de: "Sie arbeiten in Lissabon." },
          ],
        },
        words: [
          ["falar", "sprechen"],
          ["estudar", "lernen, studieren"],
          ["nós", "wir"],
          ["eles", "sie", "Plural"],
          ["a língua", "die Sprache"],
          ["o português", "Portugiesisch", "die Sprache"],
          ["o inglês", "Englisch"],
          ["um pouco", "ein bisschen"],
          ["também", "auch"],
          ["todos os dias", "jeden Tag"],
        ],
        sentences: [
          ["Falo um pouco de português.", "Ich spreche ein bisschen Portugiesisch.", ["Eu falo um pouco de português."]],
          ["Tu falas inglês?", "Sprichst du Englisch?", ["Falas inglês?"]],
          ["Nós estudamos português.", "Wir lernen Portugiesisch.", ["Estudamos português."]],
          ["Eles trabalham em Lisboa.", "Sie arbeiten in Lissabon.", ["Trabalham em Lisboa."]],
          ["Ela também fala alemão.", "Sie spricht auch Deutsch."],
          ["Estudo português todos os dias.", "Ich lerne jeden Tag Portugiesisch.", ["Eu estudo português todos os dias."]],
        ],
        sound: {
          title: "Wo liegt die Betonung?",
          body: [
            "Wörter, die auf Vokal, -s oder -m enden, betont man auf der vorletzten Silbe: fa-LA-mos, es-TU-do.",
            "Ein Akzent zeigt eine Ausnahme an: in-GLÊS, por-tu-GUÊS, tam-BÉM.",
          ],
          examples: [
            { pt: "Nós falamos português.", de: "Wir sprechen Portugiesisch." },
            { pt: "também", de: "auch" },
          ],
        },
        dialogue: {
          situation: "In einer Bar spricht dich jemand an.",
          partner: "André",
          lines: [
            ["a", "Falas português?", "Sprichst du Portugiesisch?"],
            ["b", "Falo um pouco. Estudo português todos os dias.", "Ein bisschen. Ich lerne jeden Tag Portugiesisch.", ["Falo um pouco. Eu estudo português todos os dias.", "Um pouco. Estudo português todos os dias."]],
            ["a", "Muito bem! E falas inglês?", "Sehr gut! Und sprichst du Englisch?"],
            ["b", "Sim, também falo inglês.", "Ja, ich spreche auch Englisch.", ["Sim, falo inglês também.", "Sim, eu também falo inglês."]],
            ["a", "Então falamos português!", "Dann sprechen wir Portugiesisch!"],
          ],
          question: { q: "Wie oft lernst du Portugiesisch?", options: ["Jeden Tag", "Am Wochenende", "Einmal pro Woche"] },
        },
      },
      {
        id: "pode-repetir",
        title: "Pode repetir?",
        subtitle: "Nachfragen und höflich siezen",
        grammar: {
          title: "Siezen auf Portugiesisch",
          body: [
            "Wer Fremde anspricht, benutzt die 3. Person – wie „er/sie“: „Fala inglês?“ heißt „Sprechen Sie Englisch?“.",
            "Das Pronomen lässt man meist weg. Wenn man es nennt, dann o senhor (zu einem Mann) oder a senhora (zu einer Frau). Você gibt es auch, klingt in Portugal aber oft distanziert – besser weglassen.",
            "poder (können): eu posso · tu podes · ele/ela/o senhor pode",
            "„Verstehen“ heißt in Portugal meist perceber: „Não percebo.“",
          ],
          examples: [
            { pt: "Pode repetir, se faz favor?", de: "Können Sie das bitte wiederholen?" },
            { pt: "A senhora fala inglês?", de: "Sprechen Sie Englisch? (zu einer Frau)" },
          ],
        },
        words: [
          ["o senhor", "Sie", "höflich, zu einem Mann"],
          ["a senhora", "Sie", "höflich, zu einer Frau"],
          ["pode", "Sie können, er/sie kann"],
          ["repetir", "wiederholen"],
          ["devagar", "langsam"],
          ["mais", "mehr"],
          ["perceber", "verstehen"],
          ["dizer", "sagen"],
          ["a palavra", "das Wort"],
          ["isto", "das (hier)"],
          ["saber", "wissen"],
          ["querer dizer", "bedeuten", "wörtlich: sagen wollen"],
          ["ah", "ah"],
        ],
        sentences: [
          ["Pode repetir, se faz favor?", "Können Sie das bitte wiederholen?", ["Pode repetir, por favor?"]],
          ["Mais devagar, se faz favor.", "Langsamer, bitte.", ["Mais devagar, por favor."]],
          ["Fala inglês?", "Sprechen Sie Englisch?", ["O senhor fala inglês?", "A senhora fala inglês?"]],
          ["Como se diz isto em português?", "Wie sagt man das auf Portugiesisch?"],
          ["O que quer dizer esta palavra?", "Was bedeutet dieses Wort?"],
          ["Não percebo, desculpe.", "Ich verstehe nicht, Entschuldigung.", ["Desculpe, não percebo."]],
        ],
        sound: {
          title: "Portugiesen verschlucken viel",
          body: [
            "Im schnellen Sprechen fallen unbetonte Silben fast ganz weg: „se faz favor“ klingt wie „sfasch favor“, „pode repetir“ wie „pód rrpetir“.",
            "Das ist normal – frag ruhig nach. „Mais devagar“ ist ein Satz, den Portugiesen gern hören.",
          ],
          examples: [
            { pt: "Pode repetir, se faz favor?", de: "Können Sie das bitte wiederholen?" },
            { pt: "Mais devagar, se faz favor.", de: "Langsamer, bitte." },
          ],
        },
        dialogue: {
          situation: "Eine Frau spricht dich auf der Straße an – sehr schnell.",
          partner: "Senhora",
          lines: [
            ["a", "Desculpe, sabe onde fica o museu?", "Entschuldigung, wissen Sie, wo das Museum ist?"],
            ["b", "Desculpe, não percebo. Pode repetir, se faz favor?", "Entschuldigung, ich verstehe nicht. Können Sie das bitte wiederholen?", ["Desculpe, não percebo. Pode repetir, por favor?", "Não percebo. Pode repetir, se faz favor?", "Não percebo. Pode repetir, por favor?"]],
            ["a", "Onde fica o museu?", "Wo ist das Museum?"],
            ["b", "Mais devagar, se faz favor.", "Langsamer, bitte.", ["Mais devagar, por favor."]],
            ["a", "Onde… fica… o museu?", "Wo … ist … das Museum?"],
            ["b", "Ah, o museu! É ali, à esquerda.", "Ah, das Museum! Es ist dort, links.", ["Ah, o museu! Fica ali, à esquerda."]],
          ],
          question: { q: "Was sucht die Frau?", options: ["Das Museum", "Den Bahnhof", "Die Toilette"] },
        },
      },
      {
        id: "o-que-faz",
        title: "O que faz?",
        subtitle: "Beruf und Arbeitsplatz",
        grammar: {
          title: "Berufe ohne Artikel, fazer und num",
          body: [
            "Beim Beruf steht wie im Deutschen kein Artikel: „Sou professora.“ Viele Berufe haben eine weibliche Form auf -a: médico → médica.",
            "fazer (machen): eu faço · tu fazes · ele/ela faz. „O que faz?“ ist die übliche Frage nach dem Beruf.",
            "em + um verschmilzt zu num, em + uma zu numa: „Trabalho num escritório.“",
          ],
          examples: [
            { pt: "O que faz?", de: "Was machen Sie beruflich?" },
            { pt: "Trabalho num escritório.", de: "Ich arbeite in einem Büro." },
          ],
        },
        words: [
          ["fazer", "machen, tun"],
          ["faço", "ich mache"],
          ["o professor", "der Lehrer"],
          ["a professora", "die Lehrerin"],
          ["o médico", "der Arzt"],
          ["a médica", "die Ärztin"],
          ["o estudante", "der Student"],
          ["o engenheiro", "der Ingenieur"],
          ["o empregado de mesa", "der Kellner"],
          ["o escritório", "das Büro"],
          ["o hospital", "das Krankenhaus"],
          ["a empresa", "die Firma"],
          ["interessante", "interessant"],
          ["num", "in einem", "em + um"],
          ["numa", "in einer", "em + uma"],
        ],
        sentences: [
          ["O que faz?", "Was machen Sie beruflich?", ["O que é que faz?"]],
          ["Sou professora.", "Ich bin Lehrerin.", ["Eu sou professora."]],
          ["O meu irmão é médico.", "Mein Bruder ist Arzt."],
          ["Trabalho num escritório.", "Ich arbeite in einem Büro.", ["Eu trabalho num escritório."]],
          ["Ela trabalha numa empresa alemã.", "Sie arbeitet in einer deutschen Firma."],
          ["O que fazes ao fim de semana?", "Was machst du am Wochenende?", ["O que é que fazes ao fim de semana?"]],
        ],
        sound: {
          title: "z am Wortende",
          body: [
            "z am Wortende klingt wie „sch“: faz ≈ „fasch“, dez ≈ „däsch“.",
            "Zwischen Vokalen ist z ein stimmhaftes s wie in „Rose“: fazer, dizer.",
          ],
          examples: [
            { pt: "O que faz?", de: "Was machen Sie beruflich?" },
            { pt: "fazer", de: "machen" },
          ],
        },
        dialogue: {
          situation: "Auf einer Feier fragt dich eine Frau nach deinem Beruf.",
          partner: "Doutora Helena",
          lines: [
            ["a", "O que faz?", "Was machen Sie beruflich?"],
            ["b", "Sou engenheiro. Trabalho numa empresa alemã.", "Ich bin Ingenieur. Ich arbeite in einer deutschen Firma.", ["Sou engenheira. Trabalho numa empresa alemã.", "Eu sou engenheiro. Trabalho numa empresa alemã."]],
            ["a", "Que interessante! Eu sou médica.", "Wie interessant! Ich bin Ärztin."],
            ["b", "Trabalha num hospital?", "Arbeiten Sie in einem Krankenhaus?", ["A senhora trabalha num hospital?"]],
            ["a", "Sim, no hospital de Santa Maria.", "Ja, im Krankenhaus Santa Maria."],
          ],
          question: { q: "Wo arbeitet Helena?", options: ["In einem Krankenhaus", "In einem Büro", "In einer deutschen Firma"] },
        },
      },
      {
        id: "numeros-100",
        title: "Até cem",
        subtitle: "Zahlen bis 100 und Preise",
        grammar: {
          title: "Zahlen von 11 bis 100",
          body: [
            "11–15: onze, doze, treze, catorze, quinze. 16–19 werden zusammengesetzt: dezasseis, dezassete, dezoito, dezanove – mit a, anders als in Brasilien (dezesseis).",
            "Zehner: vinte, trinta, quarenta, cinquenta, sessenta, setenta, oitenta, noventa, cem.",
            "Dazwischen verbindet man mit e: vinte e um, trinta e cinco, noventa e nove. Ab 101 heißt es cento: cento e um.",
            "Preise: „dois euros e cinquenta“ (2,50 €). Die Cents heißen in Portugal cêntimos.",
          ],
          examples: [
            { pt: "São trinta e cinco euros.", de: "Das macht 35 Euro." },
            { pt: "Tenho quarenta e dois anos.", de: "Ich bin 42 Jahre alt." },
          ],
        },
        words: [
          ["onze", "elf"],
          ["doze", "zwölf"],
          ["quinze", "fünfzehn"],
          ["dezasseis", "sechzehn"],
          ["dezanove", "neunzehn"],
          ["trinta", "dreißig"],
          ["quarenta", "vierzig"],
          ["cinquenta", "fünfzig"],
          ["setenta", "siebzig"],
          ["noventa", "neunzig"],
          ["cem", "hundert"],
          ["o cêntimo", "der Cent"],
          ["o número", "die Nummer, die Zahl"],
          ["claro", "klar, natürlich"],
        ],
        sentences: [
          ["São trinta e cinco euros.", "Das macht 35 Euro."],
          ["Tenho quarenta e dois anos.", "Ich bin 42 Jahre alt.", ["Eu tenho quarenta e dois anos."]],
          ["Custa dois euros e cinquenta.", "Es kostet 2,50 Euro."],
          ["O meu pai tem setenta anos.", "Mein Vater ist 70 Jahre alt."],
          ["Moro no número quinze.", "Ich wohne in Hausnummer 15.", ["Eu moro no número quinze."]],
          ["Quanto é, se faz favor?", "Was macht das, bitte?", ["Quanto é, por favor?"]],
        ],
        sound: {
          title: "qu: mal k, mal kw",
          body: [
            "Vor a und o spricht man qu wie „kw“: quanto, quarenta, cinquenta.",
            "Vor e und i meist wie „k“: que, quinze, quero.",
          ],
          examples: [
            { pt: "Quanto é?", de: "Was macht das?" },
            { pt: "quinze, quarenta", de: "fünfzehn, vierzig" },
          ],
        },
        dialogue: {
          situation: "Du bezahlst im Restaurant.",
          partner: "Empregado",
          lines: [
            ["b", "Quanto é, se faz favor?", "Was macht das, bitte?", ["Quanto é, por favor?", "A conta, se faz favor.", "A conta, por favor."]],
            ["a", "São trinta e cinco euros e cinquenta.", "Das macht fünfunddreißig Euro fünfzig."],
            ["b", "Posso pagar com cartão?", "Kann ich mit Karte bezahlen?"],
            ["a", "Claro.", "Natürlich."],
            ["b", "Obrigado, bom dia!", "Danke, einen schönen Tag!", ["Obrigada, bom dia!", "Obrigado. Bom dia!", "Obrigada. Bom dia!"]],
          ],
          question: { q: "Wie viel musst du bezahlen?", options: ["35,50 €", "53,50 €", "35,15 €"] },
        },
      },
      {
        id: "rotina",
        title: "O meu dia",
        subtitle: "Tagesablauf und reflexive Verben",
        grammar: {
          title: "Levanto-me: das Pronomen hinter dem Verb",
          body: [
            "Reflexive Verben erkennt man am -se: levantar-se (aufstehen), deitar-se (ins Bett gehen).",
            "In Portugal steht das Pronomen im normalen Aussagesatz hinter dem Verb: levanto-me · levantas-te · levanta-se – wie bei chamo-me.",
            "Nach não, nunca, já, também und Fragewörtern rückt es vor das Verb: „Não me levanto cedo.“",
            "Häufigkeit: sempre (immer), normalmente (normalerweise), às vezes (manchmal), nunca (nie).",
          ],
          examples: [
            { pt: "Levanto-me às sete.", de: "Ich stehe um sieben auf." },
            { pt: "Ao domingo não me levanto cedo.", de: "Sonntags stehe ich nicht früh auf." },
          ],
        },
        words: [
          ["acordar", "aufwachen"],
          ["levantar-se", "aufstehen"],
          ["deitar-se", "ins Bett gehen"],
          ["tomar duche", "duschen"],
          ["sair", "hinausgehen, losgehen"],
          ["chegar", "ankommen"],
          ["de manhã", "morgens"],
          ["à noite", "abends"],
          ["sempre", "immer"],
          ["normalmente", "normalerweise"],
          ["às vezes", "manchmal"],
          ["nunca", "nie"],
          ["te", "dich / dir", "Reflexivpronomen zu tu: levantas-te"],
        ],
        sentences: [
          ["Levanto-me às sete.", "Ich stehe um sieben auf.", ["Eu levanto-me às sete."]],
          ["Normalmente tomo duche de manhã.", "Normalerweise dusche ich morgens."],
          ["Saio de casa às oito e meia.", "Ich gehe um halb neun aus dem Haus.", ["Eu saio de casa às oito e meia."]],
          ["Ao domingo não me levanto cedo.", "Sonntags stehe ich nicht früh auf."],
          ["Às vezes chego tarde.", "Manchmal komme ich spät."],
          ["Deito-me sempre às onze.", "Ich gehe immer um elf ins Bett.", ["Eu deito-me sempre às onze."]],
        ],
        sound: {
          title: "Kleine Wörter werden ganz klein",
          body: [
            "Unbetonte kurze Wörter wie me, te, se, de, que schrumpfen fast zu einem Konsonanten: levanto-me ≈ „levãtum“, de manhã ≈ „d manjã“.",
            "Wenn du das beim Hören weißt, verstehst du schnelle Sprache viel besser.",
          ],
          examples: [
            { pt: "Levanto-me às sete.", de: "Ich stehe um sieben auf." },
            { pt: "de manhã", de: "morgens" },
          ],
        },
        dialogue: {
          situation: "Deine Mitbewohnerin fragt nach deinem Tagesablauf.",
          partner: "Beatriz",
          lines: [
            ["a", "A que horas te levantas?", "Um wie viel Uhr stehst du auf?"],
            ["b", "Levanto-me às sete. E tu?", "Ich stehe um sieben auf. Und du?", ["Eu levanto-me às sete. E tu?"]],
            ["a", "Eu levanto-me às seis e meia. Tomo duche e saio de casa às sete.", "Ich stehe um halb sieben auf. Ich dusche und gehe um sieben aus dem Haus."],
            ["b", "Eu saio de casa às oito e meia.", "Ich gehe um halb neun aus dem Haus.", ["Saio de casa às oito e meia."]],
            ["a", "E à noite?", "Und abends?"],
            ["b", "Deito-me sempre às onze.", "Ich gehe immer um elf ins Bett.", ["À noite deito-me sempre às onze.", "Eu deito-me sempre às onze."]],
          ],
          question: { q: "Wann geht Beatriz aus dem Haus?", options: ["Um sieben", "Um halb sieben", "Um halb neun"] },
        },
      },
      {
        id: "planos",
        title: "Planos",
        subtitle: "Pläne und Verabredungen",
        grammar: {
          title: "Die Zukunft mit ir + Infinitiv",
          body: [
            "Über Pläne spricht man mit ir + Infinitiv – wie „ich werde“ oder einfach Präsens im Deutschen: „Vou jantar fora.“",
            "Zur Erinnerung: eu vou · tu vais · ele/ela vai · nós vamos · eles vão",
            "querer (wollen): eu quero · tu queres · ele/ela quer. „Queres …?“ ist eine lockere Einladung.",
            "ir a + Artikel verschmilzt: ao cinema, à praia. „Heute Abend“ heißt in Portugal oft logo à noite.",
          ],
          examples: [
            { pt: "Logo à noite vou ao cinema.", de: "Heute Abend gehe ich ins Kino." },
            { pt: "Queres ir ao cinema comigo?", de: "Willst du mit mir ins Kino gehen?" },
          ],
        },
        words: [
          ["querer", "wollen"],
          ["quero", "ich will"],
          ["vamos", "wir gehen, lass uns"],
          ["logo à noite", "heute Abend"],
          ["o cinema", "das Kino"],
          ["os amigos", "die Freunde"],
          ["comigo", "mit mir"],
          ["visitar", "besuchen"],
          ["jantar fora", "auswärts essen"],
          ["descansar", "sich ausruhen"],
          ["talvez", "vielleicht"],
          ["combinado", "abgemacht"],
          ["ir", "gehen, fahren"],
        ],
        sentences: [
          ["Logo à noite vou ao cinema.", "Heute Abend gehe ich ins Kino."],
          ["Amanhã vamos jantar fora.", "Morgen gehen wir auswärts essen."],
          ["O que vais fazer no fim de semana?", "Was hast du am Wochenende vor?"],
          ["Vou visitar os meus pais.", "Ich besuche meine Eltern.", ["Eu vou visitar os meus pais."]],
          ["Queres ir ao cinema comigo?", "Willst du mit mir ins Kino gehen?", ["Tu queres ir ao cinema comigo?"]],
          ["Combinado, até logo!", "Abgemacht, bis später!"],
        ],
        sound: {
          title: "ou klingt wie ô",
          body: [
            "ou spricht man in Portugal wie ein geschlossenes „ô“: vou ≈ „vô“, sou ≈ „ßô“, estou ≈ „schtô“.",
            "Das u hört man dabei kaum.",
          ],
          examples: [
            { pt: "Vou ao cinema.", de: "Ich gehe ins Kino." },
            { pt: "Sou alemão.", de: "Ich bin Deutscher." },
          ],
        },
        dialogue: {
          situation: "Eine Freundin schreibt dir und ruft dann an.",
          partner: "Rita",
          lines: [
            ["a", "O que vais fazer no fim de semana?", "Was hast du am Wochenende vor?"],
            ["b", "Vou visitar os meus pais. E tu?", "Ich besuche meine Eltern. Und du?", ["Eu vou visitar os meus pais. E tu?"]],
            ["a", "Eu vou descansar. Queres ir ao cinema logo à noite?", "Ich ruhe mich aus. Willst du heute Abend ins Kino gehen?"],
            ["b", "Sim! A que horas?", "Ja! Um wie viel Uhr?", ["Sim, a que horas?", "Quero! A que horas?"]],
            ["a", "Às nove.", "Um neun."],
            ["b", "Combinado, até logo!", "Abgemacht, bis später!", ["Combinado! Até logo!"]],
          ],
          question: { q: "Wann geht ihr ins Kino?", options: ["Heute Abend um neun", "Am Wochenende", "Morgen früh"] },
        },
      },
    ],
};
