import type { UnitDef } from "./types";

/**
 * Kursinhalt – europäisches Portugiesisch (pt-PT), Niveau A0–A1.
 * Neue Lektionen einfach hier ergänzen; IDs von Vokabeln/Sätzen werden
 * automatisch aus dem portugiesischen Text abgeleitet.
 */
export const course: UnitDef[] = [
  {
    id: "u1",
    title: "Primeiros passos",
    description: "Begrüßen, sich vorstellen, Herkunft und Zahlen",
    lessons: [
      {
        id: "ola",
        title: "Olá!",
        subtitle: "Begrüßung und Höflichkeit",
        grammar: {
          title: "Obrigado oder obrigada?",
          body: [
            "„Danke“ richtet sich nach der Person, die spricht: Männer sagen obrigado, Frauen sagen obrigada.",
            "Bom dia sagt man bis etwa 12 Uhr, danach boa tarde. Ab der Dunkelheit heißt es boa noite – das gilt für Begrüßung und Abschied.",
            "Aussprache: Unbetonte e am Wortende werden in Portugal fast verschluckt. „Boa noite“ klingt eher wie „boa noit’“.",
          ],
          examples: [
            { pt: "Obrigado!", de: "Danke! (Mann)" },
            { pt: "Obrigada!", de: "Danke! (Frau)" },
            { pt: "Boa noite!", de: "Guten Abend! / Gute Nacht!" },
          ],
        },
        words: [
          ["olá", "hallo"],
          ["bom dia", "guten Morgen"],
          ["boa tarde", "guten Tag", "ab Mittag"],
          ["boa noite", "guten Abend"],
          ["adeus", "auf Wiedersehen"],
          ["até logo", "bis später"],
          ["obrigado", "danke", "wenn ein Mann spricht"],
          ["obrigada", "danke", "wenn eine Frau spricht"],
          ["por favor", "bitte"],
          ["sim", "ja"],
          ["não", "nein"],
          ["desculpe", "Entschuldigung"],
        ],
        sentences: [
          ["Olá, bom dia!", "Hallo, guten Morgen!"],
          ["Boa noite e obrigado.", "Guten Abend und danke."],
          ["Sim, por favor.", "Ja, bitte."],
          ["Não, obrigada.", "Nein, danke."],
          ["Até logo!", "Bis später!"],
          ["Desculpe, não percebo.", "Entschuldigung, ich verstehe nicht."],
        ],
      },
      {
        id: "quem-es",
        title: "Quem és tu?",
        subtitle: "Sich vorstellen mit ser",
        grammar: {
          title: "Das Verb ser (sein)",
          body: [
            "Ser beschreibt, wer oder was jemand ist: Name, Herkunft, Beruf, Eigenschaften.",
            "eu sou · tu és · ele/ela é · nós somos · eles/elas são",
            "Das Subjektpronomen kann man weglassen, die Verbform zeigt die Person: „Sou alemão“ reicht.",
            "„Ich heiße“ ist chamo-me. In Portugal steht das Pronomen im Aussagesatz hinter dem Verb, mit Bindestrich. Nach Fragewörtern rückt es davor: „Como te chamas?“",
          ],
          examples: [
            { pt: "Chamo-me Ana.", de: "Ich heiße Ana." },
            { pt: "Como te chamas?", de: "Wie heißt du?" },
            { pt: "Ela é portuguesa.", de: "Sie ist Portugiesin." },
          ],
        },
        words: [
          ["eu", "ich"],
          ["tu", "du"],
          ["ele", "er"],
          ["ela", "sie", "Singular"],
          ["sou", "ich bin"],
          ["és", "du bist"],
          ["é", "er/sie ist"],
          ["chamo-me", "ich heiße"],
          ["como", "wie"],
          ["muito prazer", "sehr erfreut"],
          ["alemão", "Deutscher"],
          ["alemã", "Deutsche"],
          ["português", "Portugiese"],
          ["portuguesa", "Portugiesin"],
        ],
        sentences: [
          ["Como te chamas?", "Wie heißt du?"],
          ["Chamo-me Ana.", "Ich heiße Ana."],
          ["Eu sou alemão.", "Ich bin Deutscher."],
          ["Ela é portuguesa.", "Sie ist Portugiesin."],
          ["Muito prazer!", "Sehr erfreut!"],
          ["Tu és o Pedro?", "Bist du Pedro?", ["És o Pedro?"]],
        ],
      },
      {
        id: "de-onde",
        title: "De onde és?",
        subtitle: "Herkunft und Wohnort",
        grammar: {
          title: "Verschmelzungen: da, do, na, no",
          body: [
            "Die Präpositionen de (aus, von) und em (in) verschmelzen mit dem Artikel:",
            "de + o = do · de + a = da · em + o = no · em + a = na",
            "Die meisten Länder haben einen Artikel: a Alemanha, o Brasil. Portugal und viele Städte (Lisboa) stehen ohne Artikel – aber: o Porto.",
          ],
          examples: [
            { pt: "Sou da Alemanha.", de: "Ich komme aus Deutschland." },
            { pt: "Moro em Lisboa.", de: "Ich wohne in Lissabon." },
            { pt: "Ele mora no Porto.", de: "Er wohnt in Porto." },
          ],
        },
        words: [
          ["onde", "wo"],
          ["de onde", "woher"],
          ["a Alemanha", "Deutschland"],
          ["Portugal", "Portugal"],
          ["Lisboa", "Lissabon"],
          ["moro", "ich wohne"],
          ["moras", "du wohnst"],
          ["a cidade", "die Stadt"],
          ["o país", "das Land"],
          ["bonito", "schön"],
          ["uma", "eine"],
        ],
        sentences: [
          ["De onde és?", "Woher kommst du?"],
          ["Sou da Alemanha.", "Ich komme aus Deutschland.", ["Eu sou da Alemanha."]],
          ["Moro em Lisboa.", "Ich wohne in Lissabon.", ["Eu moro em Lisboa."]],
          ["Onde moras?", "Wo wohnst du?"],
          ["Lisboa é uma cidade bonita.", "Lissabon ist eine schöne Stadt."],
          ["Ele mora no Porto.", "Er wohnt in Porto."],
        ],
      },
      {
        id: "numeros",
        title: "Números",
        subtitle: "Zahlen von 0 bis 20 und das Alter",
        grammar: {
          title: "Zahlen mit Geschlecht und das Alter",
          body: [
            "Eins und zwei passen sich dem Nomen an: um café, uma água · dois cafés, duas águas.",
            "Das Alter drückt man mit ter (haben) aus: „Tenho vinte anos“ – wörtlich „Ich habe zwanzig Jahre“.",
          ],
          examples: [
            { pt: "Quantos anos tens?", de: "Wie alt bist du?" },
            { pt: "Tenho vinte anos.", de: "Ich bin zwanzig Jahre alt." },
          ],
        },
        words: [
          ["zero", "null"],
          ["um", "eins", "männlich; weiblich: uma"],
          ["dois", "zwei", "männlich; weiblich: duas"],
          ["três", "drei"],
          ["quatro", "vier"],
          ["cinco", "fünf"],
          ["seis", "sechs"],
          ["sete", "sieben"],
          ["oito", "acht"],
          ["nove", "neun"],
          ["dez", "zehn"],
          ["vinte", "zwanzig"],
          ["tenho", "ich habe"],
          ["os anos", "die Jahre"],
        ],
        sentences: [
          ["Quantos anos tens?", "Wie alt bist du?"],
          ["Tenho vinte anos.", "Ich bin zwanzig Jahre alt.", ["Eu tenho vinte anos."]],
          ["Um café e duas águas.", "Ein Kaffee und zwei Wasser."],
          ["Ela tem oito anos.", "Sie ist acht Jahre alt."],
          ["Tenho três irmãos.", "Ich habe drei Geschwister."],
        ],
      },
    ],
  },
  {
    id: "u2",
    title: "O dia a dia",
    description: "Café, Essen, Familie und Befinden",
    lessons: [
      {
        id: "cafe",
        title: "No café",
        subtitle: "Bestellen wie in Lissabon",
        grammar: {
          title: "Höflich bestellen",
          body: [
            "Queria („ich wollte“) ist die übliche höfliche Form zum Bestellen – wie das deutsche „Ich hätte gern“.",
            "Se faz favor ist typisch für Portugal: zum Bitten und um die Bedienung zu rufen. Por favor geht auch.",
            "Uma bica ist in Lissabon ein Espresso, ein galão ein Milchkaffee im Glas.",
          ],
          examples: [
            { pt: "Queria uma bica, se faz favor.", de: "Ich hätte gern einen Espresso, bitte." },
            { pt: "A conta, se faz favor.", de: "Die Rechnung, bitte." },
          ],
        },
        words: [
          ["o café", "der Kaffee"],
          ["a bica", "der Espresso", "Lissabon"],
          ["o galão", "der Milchkaffee"],
          ["a água", "das Wasser"],
          ["o sumo", "der Saft"],
          ["a laranja", "die Orange"],
          ["o pão", "das Brot"],
          ["o pastel de nata", "das Puddingtörtchen"],
          ["queria", "ich hätte gern"],
          ["se faz favor", "bitte"],
          ["a conta", "die Rechnung"],
          ["com", "mit"],
          ["sem", "ohne"],
          ["o açúcar", "der Zucker"],
        ],
        sentences: [
          ["Queria uma bica, se faz favor.", "Ich hätte gern einen Espresso, bitte.", ["Queria uma bica, por favor."]],
          ["Um galão e um pastel de nata.", "Ein Milchkaffee und ein Puddingtörtchen."],
          ["A conta, se faz favor.", "Die Rechnung, bitte.", ["A conta, por favor."]],
          ["Um café sem açúcar.", "Ein Kaffee ohne Zucker."],
          ["Queria um sumo de laranja.", "Ich hätte gern einen Orangensaft."],
          ["Uma água com gás, se faz favor.", "Ein Wasser mit Kohlensäure, bitte.", ["Uma água com gás, por favor."]],
        ],
      },
      {
        id: "comer",
        title: "Comer e beber",
        subtitle: "Essen, Trinken, Vorlieben",
        grammar: {
          title: "Verben auf -er und gostar de",
          body: [
            "Regelmäßige Verben auf -er, z. B. comer (essen): eu como · tu comes · ele/ela come · nós comemos · eles comem",
            "Gostar (mögen) braucht immer de: gosto de peixe. Mit Artikel verschmilzt es: gosto do vinho, gosto da praia.",
            "Verneinung: não steht direkt vor dem Verb – „Não gosto de cerveja“.",
          ],
          examples: [
            { pt: "Eu gosto de peixe.", de: "Ich mag Fisch." },
            { pt: "Não gosto de cerveja.", de: "Ich mag kein Bier." },
          ],
        },
        words: [
          ["comer", "essen"],
          ["beber", "trinken"],
          ["gosto de", "ich mag"],
          ["o peixe", "der Fisch"],
          ["a carne", "das Fleisch"],
          ["o vinho", "der Wein"],
          ["a cerveja", "das Bier"],
          ["o pequeno-almoço", "das Frühstück"],
          ["o almoço", "das Mittagessen"],
          ["o jantar", "das Abendessen"],
          ["muito", "sehr, viel"],
        ],
        sentences: [
          ["Eu gosto de peixe.", "Ich mag Fisch.", ["Gosto de peixe."]],
          ["Tu bebes vinho?", "Trinkst du Wein?", ["Bebes vinho?"]],
          ["Ela come carne.", "Sie isst Fleisch."],
          ["Não gosto de cerveja.", "Ich mag kein Bier.", ["Eu não gosto de cerveja."]],
          ["O jantar é às oito.", "Das Abendessen ist um acht."],
          ["Bebo café ao pequeno-almoço.", "Ich trinke Kaffee zum Frühstück.", ["Eu bebo café ao pequeno-almoço."]],
        ],
      },
      {
        id: "familia",
        title: "A família",
        subtitle: "Familie und Possessivpronomen",
        grammar: {
          title: "Mein, dein – mit Artikel",
          body: [
            "In Portugal steht vor dem Possessivpronomen normalerweise der Artikel: o meu pai, a minha mãe.",
            "o meu / a minha (mein) · o teu / a tua (dein) · os meus / as minhas (meine, Plural)",
            "Os irmãos kann „die Brüder“ oder „die Geschwister“ bedeuten, os pais sind „die Eltern“.",
          ],
          examples: [
            { pt: "Esta é a minha mãe.", de: "Das ist meine Mutter." },
            { pt: "Os meus pais moram em Faro.", de: "Meine Eltern wohnen in Faro." },
          ],
        },
        words: [
          ["o pai", "der Vater"],
          ["a mãe", "die Mutter"],
          ["os pais", "die Eltern"],
          ["o irmão", "der Bruder"],
          ["a irmã", "die Schwester"],
          ["os irmãos", "die Geschwister"],
          ["o filho", "der Sohn"],
          ["a filha", "die Tochter"],
          ["o meu", "mein"],
          ["a minha", "meine"],
          ["esta", "diese, das (hier)"],
        ],
        sentences: [
          ["Esta é a minha mãe.", "Das ist meine Mutter."],
          ["Tenho uma irmã.", "Ich habe eine Schwester.", ["Eu tenho uma irmã."]],
          ["O meu pai chama-se João.", "Mein Vater heißt João."],
          ["Os meus pais moram em Faro.", "Meine Eltern wohnen in Faro."],
          ["Tens irmãos?", "Hast du Geschwister?", ["Tu tens irmãos?"]],
          ["A minha filha tem dez anos.", "Meine Tochter ist zehn Jahre alt."],
        ],
      },
      {
        id: "estar",
        title: "Ser ou estar?",
        subtitle: "Befinden, Zustand, Ort",
        grammar: {
          title: "Estar und die Verlaufsform",
          body: [
            "Estar (sein) beschreibt Vorübergehendes: Befinden, Stimmung, Aufenthaltsort. Ser beschreibt, was dauerhaft ist.",
            "eu estou · tu estás · ele/ela está · nós estamos · eles estão",
            "„Gerade etwas tun“ heißt in Portugal estar a + Infinitiv: „Estou a trabalhar“. Die brasilianische Form „estou trabalhando“ klingt hier fremd.",
          ],
          examples: [
            { pt: "Como estás?", de: "Wie geht es dir?" },
            { pt: "Estou a trabalhar.", de: "Ich arbeite gerade." },
          ],
        },
        words: [
          ["estou", "ich bin (Zustand)"],
          ["estás", "du bist (Zustand)"],
          ["está", "er/sie ist (Zustand)"],
          ["bem", "gut"],
          ["mal", "schlecht"],
          ["cansado", "müde"],
          ["contente", "froh"],
          ["hoje", "heute"],
          ["aqui", "hier"],
          ["em casa", "zu Hause"],
          ["trabalhar", "arbeiten"],
        ],
        sentences: [
          ["Como estás?", "Wie geht es dir?"],
          ["Estou bem, obrigado.", "Mir geht es gut, danke.", ["Eu estou bem, obrigado.", "Estou bem, obrigada."]],
          ["Hoje estou cansada.", "Heute bin ich müde.", ["Hoje estou cansado."]],
          ["Ela está em casa.", "Sie ist zu Hause."],
          ["Estou a trabalhar.", "Ich arbeite gerade.", ["Eu estou a trabalhar."]],
          ["O Pedro está aqui?", "Ist Pedro hier?"],
        ],
      },
    ],
  },
  {
    id: "u3",
    title: "Na cidade",
    description: "Wege, Verkehrsmittel, Einkaufen und Zeit",
    lessons: [
      {
        id: "onde-fica",
        title: "Onde fica?",
        subtitle: "Nach dem Weg fragen",
        grammar: {
          title: "Ficar für Orte",
          body: [
            "Für die Lage von Orten sagt man in Portugal gern ficar: „Onde fica a estação?“ – Wo ist der Bahnhof?",
            "Richtungen: à esquerda (links), à direita (rechts), em frente (geradeaus).",
            "Desculpe ist die höfliche Art, jemanden anzusprechen.",
          ],
          examples: [
            { pt: "Onde fica a estação?", de: "Wo ist der Bahnhof?" },
            { pt: "É ali, à direita.", de: "Es ist dort, rechts." },
          ],
        },
        words: [
          ["onde fica", "wo ist"],
          ["a rua", "die Straße"],
          ["a estação", "der Bahnhof"],
          ["a praia", "der Strand"],
          ["o museu", "das Museum"],
          ["a casa de banho", "die Toilette"],
          ["perto", "nah"],
          ["longe", "weit weg"],
          ["à esquerda", "links"],
          ["à direita", "rechts"],
          ["em frente", "geradeaus"],
          ["ali", "dort"],
        ],
        sentences: [
          ["Onde fica a estação?", "Wo ist der Bahnhof?"],
          ["Desculpe, onde fica a casa de banho?", "Entschuldigung, wo ist die Toilette?"],
          ["É ali, à direita.", "Es ist dort, rechts."],
          ["A praia fica perto.", "Der Strand ist nah."],
          ["Siga em frente.", "Gehen Sie geradeaus."],
          ["O museu fica longe?", "Ist das Museum weit weg?"],
        ],
      },
      {
        id: "transportes",
        title: "Transportes",
        subtitle: "Zug, Bus und Straßenbahn",
        grammar: {
          title: "Ir und apanhar",
          body: [
            "Ir (gehen, fahren): eu vou · tu vais · ele/ela vai · nós vamos · eles vão",
            "Ein Verkehrsmittel „nehmen“ heißt in Portugal apanhar: apanhar o autocarro. Das brasilianische „pegar“ solltest du hier vermeiden.",
            "Einige Wörter sind typisch europäisch: o comboio (Zug), o autocarro (Bus), o elétrico (Straßenbahn).",
          ],
          examples: [
            { pt: "Vou apanhar o autocarro.", de: "Ich nehme den Bus." },
            { pt: "Vou a pé.", de: "Ich gehe zu Fuß." },
          ],
        },
        words: [
          ["o comboio", "der Zug"],
          ["o autocarro", "der Bus"],
          ["o elétrico", "die Straßenbahn"],
          ["o metro", "die U-Bahn"],
          ["o bilhete", "die Fahrkarte"],
          ["a paragem", "die Haltestelle"],
          ["apanhar", "nehmen (Verkehrsmittel)"],
          ["vou", "ich gehe, ich fahre"],
          ["para", "nach, zu"],
          ["a pé", "zu Fuß"],
          ["quando", "wann"],
        ],
        sentences: [
          ["Vou apanhar o autocarro.", "Ich nehme den Bus.", ["Eu vou apanhar o autocarro."]],
          ["Onde fica a paragem?", "Wo ist die Haltestelle?"],
          ["Um bilhete para o Porto, se faz favor.", "Eine Fahrkarte nach Porto, bitte.", ["Um bilhete para o Porto, por favor."]],
          ["Quando parte o comboio?", "Wann fährt der Zug ab?"],
          ["Vou a pé.", "Ich gehe zu Fuß.", ["Eu vou a pé."]],
          ["Apanho o elétrico.", "Ich nehme die Straßenbahn.", ["Eu apanho o elétrico."]],
        ],
      },
      {
        id: "compras",
        title: "Às compras",
        subtitle: "Einkaufen und bezahlen",
        grammar: {
          title: "Preise und Mengen",
          body: [
            "Nach dem Preis fragt man mit „Quanto custa?“ (Was kostet das?), bei mehreren Dingen „Quanto custam?“.",
            "Mengenangaben mit de: um quilo de maçãs, uma garrafa de água.",
            "Posso …? (Kann ich …?) + Infinitiv: „Posso pagar com cartão?“",
          ],
          examples: [
            { pt: "Quanto custa?", de: "Was kostet das?" },
            { pt: "São cinco euros.", de: "Das macht fünf Euro." },
          ],
        },
        words: [
          ["quanto custa", "was kostet"],
          ["caro", "teuer"],
          ["barato", "billig"],
          ["o mercado", "der Markt"],
          ["a loja", "das Geschäft"],
          ["a fruta", "das Obst"],
          ["a maçã", "der Apfel"],
          ["o quilo", "das Kilo"],
          ["pagar", "bezahlen"],
          ["o cartão", "die Karte"],
          ["o dinheiro", "das Geld"],
          ["posso", "ich kann, darf ich"],
        ],
        sentences: [
          ["Quanto custa?", "Was kostet das?"],
          ["É muito caro.", "Das ist sehr teuer."],
          ["Queria um quilo de maçãs.", "Ich hätte gern ein Kilo Äpfel."],
          ["Posso pagar com cartão?", "Kann ich mit Karte bezahlen?"],
          ["São cinco euros.", "Das macht fünf Euro."],
          ["Mais alguma coisa?", "Sonst noch etwas?"],
        ],
      },
      {
        id: "horas",
        title: "As horas",
        subtitle: "Uhrzeit und Verabredungen",
        grammar: {
          title: "Wie spät ist es?",
          body: [
            "Bei einer Stunde steht é, sonst são: é uma hora · são duas horas · são três e meia.",
            "e meia = halb (nach der vollen Stunde!): „São três e meia“ ist halb vier. e um quarto = Viertel nach, menos um quarto = Viertel vor.",
            "„Um“ bei Uhrzeiten: às – „às oito“ (um acht), aber „à uma“ (um eins).",
          ],
          examples: [
            { pt: "Que horas são?", de: "Wie spät ist es?" },
            { pt: "São três e meia.", de: "Es ist halb vier." },
          ],
        },
        words: [
          ["que horas são", "wie spät ist es"],
          ["a hora", "die Stunde, die Uhrzeit"],
          ["e meia", "halb (… und dreißig)"],
          ["e um quarto", "Viertel nach"],
          ["menos um quarto", "Viertel vor"],
          ["o meio-dia", "der Mittag"],
          ["a meia-noite", "die Mitternacht"],
          ["agora", "jetzt"],
          ["cedo", "früh"],
          ["tarde", "spät"],
          ["às", "um (Uhrzeit)"],
        ],
        sentences: [
          ["Que horas são?", "Wie spät ist es?"],
          ["São três e meia.", "Es ist halb vier."],
          ["É meio-dia.", "Es ist Mittag."],
          ["O museu abre às dez.", "Das Museum öffnet um zehn."],
          ["Já é tarde.", "Es ist schon spät."],
          ["Chego às oito e um quarto.", "Ich komme um Viertel nach acht an."],
        ],
      },
      {
        id: "semana",
        title: "A semana",
        subtitle: "Wochentage und Pläne",
        grammar: {
          title: "Wochentage auf Portugiesisch",
          body: [
            "Die Werktage werden gezählt: segunda-feira (Montag) bis sexta-feira (Freitag). Im Alltag lässt man -feira oft weg: „Até segunda!“",
            "Sábado und domingo haben eigene Namen.",
            "„Sonntags“ (regelmäßig) heißt ao domingo, „am Sonntag“ (einmalig) no domingo.",
          ],
          examples: [
            { pt: "Hoje é sexta-feira.", de: "Heute ist Freitag." },
            { pt: "Ao domingo não trabalho.", de: "Sonntags arbeite ich nicht." },
          ],
        },
        words: [
          ["segunda-feira", "Montag"],
          ["terça-feira", "Dienstag"],
          ["quarta-feira", "Mittwoch"],
          ["quinta-feira", "Donnerstag"],
          ["sexta-feira", "Freitag"],
          ["o sábado", "der Samstag"],
          ["o domingo", "der Sonntag"],
          ["a semana", "die Woche"],
          ["o fim de semana", "das Wochenende"],
          ["amanhã", "morgen"],
          ["ontem", "gestern"],
        ],
        sentences: [
          ["Hoje é sexta-feira.", "Heute ist Freitag."],
          ["Amanhã vou à praia.", "Morgen gehe ich an den Strand."],
          ["Ao domingo não trabalho.", "Sonntags arbeite ich nicht."],
          ["Bom fim de semana!", "Schönes Wochenende!"],
          ["Até segunda!", "Bis Montag!"],
          ["Ontem foi quarta-feira.", "Gestern war Mittwoch."],
        ],
      },
    ],
  },
];
