import type { UnitLexicon } from "../types";

export const u1: UnitLexicon = {
  words: {
    "olá": { pos: "phrase" },
    "bom dia": { pos: "phrase", sound: "bõ DIa" },
    "boa tarde": { pos: "phrase", sound: "BOa TARd" },
    "boa noite": { pos: "phrase", sound: "BOa NOIT" },
    "adeus": { pos: "phrase", sound: "aDEUsch" },
    "até logo": { pos: "phrase", sound: "aTÄ LOgu" },
    "obrigado": { pos: "phrase", sound: "obriGAdu" },
    "obrigada": { pos: "phrase", sound: "obriGAda" },
    "por favor": { pos: "phrase", sound: "pur faWOR" },
    "sim": { pos: "adv" },
    "não": { pos: "adv", sound: "NÃU" },
    "desculpe": { pos: "phrase", verb: "desculpar", sound: "dschKULP" },
    "e": { pos: "conj", sound: "i" },
    "percebo": { pos: "verb", verb: "perceber", sound: "purßEbu" },
    "de nada": { pos: "phrase", sound: "d NAda" },
    "eu": { pos: "pron", sound: "EU" },
    "tu": { pos: "pron" },
    "ele": { pos: "pron", sound: "EL" },
    "ela": { pos: "pron", sound: "ÄLa" },
    "sou": { pos: "verb", verb: "ser", sound: "ßo" },
    "és": { pos: "verb", verb: "ser", sound: "äsch" },
    "é": { pos: "verb", verb: "ser", sound: "ä" },
    "chamo-me": { pos: "verb", verb: "chamar-se", sound: "SCHAmu m" },
    "como": { pos: "question", sound: "KOmu" },
    "muito prazer": { pos: "phrase", sound: "MUINtu praSER" },
    "alemão": { pos: "noun", sound: "alMÃU" },
    "alemã": { pos: "noun", sound: "alMÃ" },
    "português": { pos: "noun", sound: "purtuGESCH" },
    "portuguesa": { pos: "noun", sound: "purtuGEsa" },
    "o": { pos: "art", sound: "u" },
    "te chamas": { pos: "verb", verb: "chamar-se", sound: "t SCHAmasch" },
    "onde": { pos: "question", sound: "Ond" },
    "de onde": { pos: "question", sound: "d Ond" },
    "a Alemanha": { pos: "noun", sound: "a alMAnja" },
    "Portugal": { pos: "noun", sound: "purtuGAL" },
    "Lisboa": { pos: "noun", sound: "lischBOa" },
    "moro": { pos: "verb", verb: "morar", sound: "MOru" },
    "moras": { pos: "verb", verb: "morar", sound: "MOrasch" },
    "a cidade": { pos: "noun", sound: "a ßiDAD" },
    "o país": { pos: "noun", sound: "u paISCH" },
    "bonito": { pos: "adj", sound: "buNItu" },
    "uma": { pos: "art", sound: "Uma" },
    "em": { pos: "prep", sound: "ÃI" },
    "da": { pos: "prep" },
    "do": { pos: "prep", sound: "du" },
    "no": { pos: "prep", sound: "nu" },
    "na": { pos: "prep" },
    "mas": { pos: "conj", sound: "MASCH" },
    "zero": { pos: "num", sound: "SEru" },
    "um": { pos: "num" },
    "dois": { pos: "num", sound: "DOISCH" },
    "três": { pos: "num", sound: "TRESCH" },
    "quatro": { pos: "num", sound: "KWAtru" },
    "cinco": { pos: "num", sound: "ßINku" },
    "seis": { pos: "num", sound: "ßÄISCH" },
    "sete": { pos: "num", sound: "ßÄT" },
    "oito": { pos: "num", sound: "OItu" },
    "nove": { pos: "num", sound: "NOW" },
    "dez": { pos: "num", sound: "DÄSCH" },
    "vinte": { pos: "num", sound: "WINT" },
    "tenho": { pos: "verb", verb: "ter", sound: "TÄNju" },
    "os anos": { pos: "noun", sound: "usch ANusch" },
    "quantos": { pos: "question", sound: "KWANtusch" },
    "também": { pos: "adv", sound: "tãmBÃI" },
    "o café": { pos: "noun", sound: "u kaFÄ" },
    "a água": { pos: "noun", sound: "a AGwa" },
    "o irmão": { pos: "noun", sound: "u irMÃU" },
  },
  forms: {
    "bonita": "bonito",
    "duas": "dois",
    "águas": "a água",
    "irmãos": "o irmão",
    "irmã": "o irmão",
  },
  names: ["Ana", "Pedro", "Tom", "Inês", "Porto", "Berlim"],
};
