import type { UnitLexicon } from "../types";

export const u2: UnitLexicon = {
  words: {
    // cafe
    "a bica": { pos: "noun" },
    "o galão": { pos: "noun", sound: "gaLÃU" },
    "o sumo": { pos: "noun", sound: "ßUmu" },
    "a laranja": { pos: "noun", sound: "laRÃNscha" },
    "o pão": { pos: "noun", sound: "PÃU" },
    "o pastel de nata": { pos: "noun", sound: "paschTÄL d NAta" },
    "queria": { pos: "verb", verb: "querer", sound: "kiRIa" },
    "se faz favor": { pos: "phrase", verb: "fazer", sound: "ß fasch faWOR" },
    "a conta": { pos: "noun", sound: "KÕnta" },
    "com": { pos: "prep", sound: "KÕ" },
    "sem": { pos: "prep", sound: "ßÃI" },
    "o açúcar": { pos: "noun", sound: "aßUkar" },
    "o gás": { pos: "noun", sound: "GASCH" },
    "que": { pos: "pron", sound: "k" },
    "desejar": { pos: "verb", verb: "desejar" },
    "mais": { pos: "adv", sound: "MAISCH" },
    "alguma coisa": { pos: "pron", sound: "alGUma KOIsa" },
    // comer
    "comer": { pos: "verb", verb: "comer", sound: "kuMER" },
    "beber": { pos: "verb", verb: "beber", sound: "bBER" },
    "gosto de": { pos: "verb", verb: "gostar", sound: "GOschtu d" },
    "o peixe": { pos: "noun", sound: "PÄISCH" },
    "a carne": { pos: "noun", sound: "KARn" },
    "o vinho": { pos: "noun", sound: "WInju" },
    "a cerveja": { pos: "noun", sound: "ßrWÄIscha" },
    "o pequeno-almoço": { pos: "noun", sound: "pKEnu alMOßu" },
    "o almoço": { pos: "noun", sound: "alMOßu" },
    "o jantar": { pos: "noun", sound: "schãnTAR" },
    "muito": { pos: "adv", sound: "MUINtu" },
    "muito bem": { pos: "phrase", sound: "MUINtu BÃI" },
    "ao": { pos: "prep" },
    "às": { pos: "prep", sound: "ASCH" },
    "ou": { pos: "conj", sound: "O" },
    // familia
    "o pai": { pos: "noun", sound: "PAI" },
    "a mãe": { pos: "noun", sound: "MÃI" },
    "os pais": { pos: "noun", sound: "PAISCH" },
    "a irmã": { pos: "noun", sound: "irMÃ" },
    "os irmãos": { pos: "noun", sound: "irMÃUSCH" },
    "o filho": { pos: "noun", sound: "FIlju" },
    "a filha": { pos: "noun", sound: "FIlja" },
    "o meu": { pos: "pron", sound: "u MÄU" },
    "a minha": { pos: "pron", sound: "a MInja" },
    "esta": { pos: "pron", sound: "ÄSCHta" },
    "este": { pos: "pron", sound: "ÄSCHT" },
    "chamar-se": { pos: "verb", verb: "chamar-se", sound: "schaMAR ß" },
    "morar": { pos: "verb", verb: "morar", sound: "muRAR" },
    "ter": { pos: "verb", verb: "ter", sound: "TÄI" },
    "quem": { pos: "question", sound: "KÃI" },
    // estar
    "estou": { pos: "verb", verb: "estar", sound: "schTO" },
    "estás": { pos: "verb", verb: "estar", sound: "schTASCH" },
    "está": { pos: "verb", verb: "estar", sound: "schTA" },
    "bem": { pos: "adv", sound: "BÃI" },
    "mal": { pos: "adv" },
    "cansado": { pos: "adj", sound: "kãnSAdu" },
    "contente": { pos: "adj", sound: "kõnTENT" },
    "hoje": { pos: "adv", sound: "OSCH" },
    "aqui": { pos: "adv", sound: "aKI" },
    "em casa": { pos: "phrase", sound: "ãi KAsa" },
    "trabalhar": { pos: "verb", verb: "trabalhar", sound: "trabaLJAR" },
  },
  forms: {
    "meus": "o meu",
    "cansada": "cansado",
  },
  names: ["João", "Ana", "Faro", "Hamburgo", "Pedro"],
};
