import type { UnitLexicon } from "../types";

export const u3: UnitLexicon = {
  words: {
    // onde-fica
    "onde fica": { pos: "phrase", verb: "ficar", sound: "ONd FIka" },
    "a rua": { pos: "noun", sound: "a RRUa" },
    "a estação": { pos: "noun", sound: "aschtaßÃU" },
    "a praia": { pos: "noun", sound: "a PRAja" },
    "o museu": { pos: "noun", sound: "u muSEU" },
    "a casa de banho": { pos: "noun", sound: "a KAsa d BANju" },
    "perto": { pos: "adv", sound: "PÄRtu" },
    "longe": { pos: "adv", sound: "LÕNsch" },
    "à esquerda": { pos: "adv", sound: "a schKÄRda" },
    "à direita": { pos: "adv", sound: "a diRÄIta" },
    "em frente": { pos: "adv", sound: "ãi FRÄNT" },
    "ali": { pos: "adv", sound: "aLI" },
    "siga": { pos: "verb", verb: "seguir", sound: "ßIga" },
    "depois": { pos: "adv", sound: "dPOISCH" },
    // transportes
    "o comboio": { pos: "noun", sound: "kõmBOIu" },
    "o autocarro": { pos: "noun", sound: "autuKArru" },
    "o elétrico": { pos: "noun", sound: "iLÄtriku" },
    "o metro": { pos: "noun", sound: "u MÄtru" },
    "o bilhete": { pos: "noun", sound: "u biLJET" },
    "a paragem": { pos: "noun", sound: "paRAschãi" },
    "apanhar": { pos: "verb", verb: "apanhar", sound: "apaNJAR" },
    "vou": { pos: "verb", verb: "ir", sound: "WO" },
    "para": { pos: "prep", sound: "PRA" },
    "a pé": { pos: "adv", sound: "a PÄ" },
    "quando": { pos: "question", sound: "KWANdu" },
    "partir": { pos: "verb", verb: "partir", sound: "parTIR" },
    "o euro": { pos: "noun", sound: "u ÄUru" },
    "às": { pos: "prep", sound: "ASCH" },
    // compras
    "quanto custa": { pos: "phrase", verb: "custar", sound: "KUANtu KUSchta" },
    "caro": { pos: "adj", sound: "KAru" },
    "barato": { pos: "adj", sound: "baRAtu" },
    "o mercado": { pos: "noun", sound: "u mrKAdu" },
    "a loja": { pos: "noun", sound: "a LOscha" },
    "a fruta": { pos: "noun", sound: "a FRUta" },
    "a maçã": { pos: "noun", sound: "a maßÃ" },
    "o quilo": { pos: "noun", sound: "u KIlu" },
    "pagar": { pos: "verb", verb: "pagar", sound: "paGAR" },
    "o cartão": { pos: "noun", sound: "u karTÃU" },
    "o dinheiro": { pos: "noun", sound: "u diNJÄIru" },
    "posso": { pos: "verb", verb: "poder", sound: "POßu" },
    "o que": { pos: "question", sound: "u KE" },
    // horas
    "que horas são": { pos: "phrase", verb: "ser", sound: "k ORasch ßÃU" },
    "a hora": { pos: "noun", sound: "a Ora" },
    "e meia": { pos: "phrase", sound: "i MÄIa" },
    "e um quarto": { pos: "phrase", sound: "i um KWARtu" },
    "menos um quarto": { pos: "phrase", sound: "MEnusch um KWARtu" },
    "o meio-dia": { pos: "noun", sound: "u MÄIu DIa" },
    "a meia-noite": { pos: "noun", sound: "a MÄIa NOIt" },
    "agora": { pos: "adv", sound: "aGOra" },
    "cedo": { pos: "adv", sound: "ßEdu" },
    "tarde": { pos: "adv", sound: "TARd" },
    "abrir": { pos: "verb", verb: "abrir", sound: "aBRIR" },
    "já": { pos: "adv", sound: "SCHA" },
    "chegar": { pos: "verb", verb: "chegar", sound: "scheGAR" },
    "ainda": { pos: "adv", sound: "aINda" },
    // semana
    "segunda-feira": { pos: "noun", sound: "ßGUNda FÄIra" },
    "terça-feira": { pos: "noun", sound: "TERßa FÄIra" },
    "quarta-feira": { pos: "noun", sound: "KWARta FÄIra" },
    "quinta-feira": { pos: "noun", sound: "KINta FÄIra" },
    "sexta-feira": { pos: "noun", sound: "ßÄIschta FÄIra" },
    "o sábado": { pos: "noun", sound: "u ßAbadu" },
    "o domingo": { pos: "noun", sound: "u duMINgu" },
    "a semana": { pos: "noun", sound: "a ßMAna" },
    "o fim de semana": { pos: "noun", sound: "u FIM d ßMAna" },
    "amanhã": { pos: "adv", sound: "amaNJÃ" },
    "ontem": { pos: "adv", sound: "ONtãi" },
    "então": { pos: "adv", sound: "ãiTÃU" },
  },
  forms: {
    "maçãs": "a maçã",
    "euros": "o euro",
  },
  names: ["Porto"],
};
