import type { UnitLexicon } from "../types";

export const u4: UnitLexicon = {
  words: {
    // falo
    "falar": { pos: "verb", verb: "falar", sound: "faLAR" },
    "estudar": { pos: "verb", verb: "estudar", sound: "schtuDAR" },
    "nós": { pos: "pron" },
    "eles": { pos: "pron", sound: "ELSCH" },
    "a língua": { pos: "noun", sound: "a LINgwa" },
    "o português": { pos: "noun", sound: "u purtuGESCH" },
    "o inglês": { pos: "noun", sound: "u inGLESCH" },
    "um pouco": { pos: "phrase", sound: "um POku" },
    "todos os dias": { pos: "phrase", sound: "TOdusch usch DIasch" },
    // pode-repetir
    "o senhor": { pos: "noun", sound: "u ßNJOR" },
    "a senhora": { pos: "noun", sound: "a ßNJOra" },
    "pode": { pos: "verb", verb: "poder", sound: "PODe" },
    "repetir": { pos: "verb", verb: "repetir", sound: "rrpeTIR" },
    "devagar": { pos: "adv", sound: "dwaGAR" },
    "perceber": { pos: "verb", verb: "perceber", sound: "prßeBER" },
    "dizer": { pos: "verb", verb: "dizer", sound: "diSER" },
    "a palavra": { pos: "noun", sound: "a paLAwra" },
    "isto": { pos: "pron", sound: "ISCHtu" },
    "saber": { pos: "verb", verb: "saber", sound: "ßaBER" },
    "querer dizer": { pos: "verb", verb: "querer", sound: "kEREr diSER" },
    "ah": { pos: "phrase" },
    // o-que-faz
    "fazer": { pos: "verb", verb: "fazer", sound: "faSER" },
    "faço": { pos: "verb", verb: "fazer", sound: "FAßu" },
    "o professor": { pos: "noun", sound: "u prufßOR" },
    "a professora": { pos: "noun", sound: "a prufßOra" },
    "o médico": { pos: "noun", sound: "u MÄdiku" },
    "a médica": { pos: "noun", sound: "a MÄdika" },
    "o estudante": { pos: "noun", sound: "u schtuDANT" },
    "o engenheiro": { pos: "noun", sound: "u ãischNJÄIru" },
    "o empregado de mesa": { pos: "noun", sound: "u ãiprGAdu d MEsa" },
    "o escritório": { pos: "noun", sound: "u schkriTOriu" },
    "o hospital": { pos: "noun", sound: "u oschpiTAL" },
    "a empresa": { pos: "noun", sound: "a ãiPREsa" },
    "interessante": { pos: "adj", sound: "intrßÃNT" },
    "num": { pos: "prep" },
    "numa": { pos: "prep" },
    // numeros-100
    "onze": { pos: "num", sound: "ÕS" },
    "doze": { pos: "num", sound: "DOS" },
    "quinze": { pos: "num", sound: "KINS" },
    "dezasseis": { pos: "num", sound: "dsaßÄISCH" },
    "dezanove": { pos: "num", sound: "dsaNOW" },
    "trinta": { pos: "num", sound: "TRINta" },
    "quarenta": { pos: "num", sound: "kwaRENta" },
    "cinquenta": { pos: "num", sound: "ßinKWENta" },
    "setenta": { pos: "num", sound: "ßTENta" },
    "noventa": { pos: "num", sound: "nuWENta" },
    "cem": { pos: "num", sound: "ßÃI" },
    "o cêntimo": { pos: "noun", sound: "u ßENtimu" },
    "o número": { pos: "noun", sound: "u NUmeru" },
    "claro": { pos: "adj", sound: "KLAru" },
    // rotina
    "acordar": { pos: "verb", verb: "acordar", sound: "akurDAR" },
    "levantar-se": { pos: "verb", verb: "levantar-se", sound: "lwãnTARß" },
    "deitar-se": { pos: "verb", verb: "deitar-se", sound: "däiTARß" },
    "tomar duche": { pos: "verb", verb: "tomar", sound: "tuMAR DUsch" },
    "sair": { pos: "verb", verb: "sair", sound: "ßaIR" },
    "de manhã": { pos: "phrase", sound: "d maNJÃ" },
    "à noite": { pos: "phrase", sound: "a NOIT" },
    "sempre": { pos: "adv", sound: "ßEMPR" },
    "normalmente": { pos: "adv", sound: "normalMENT" },
    "às vezes": { pos: "phrase", sound: "asch WEsesch" },
    "nunca": { pos: "adv", sound: "NUNka" },
    "te": { pos: "pron" },
    // planos
    "querer": { pos: "verb", verb: "querer", sound: "kEREr" },
    "quero": { pos: "verb", verb: "querer", sound: "KÄru" },
    "vamos": { pos: "verb", verb: "ir", sound: "WAmusch" },
    "logo à noite": { pos: "phrase", sound: "LOgu a NOIT" },
    "o cinema": { pos: "noun", sound: "u ßiNEma" },
    "os amigos": { pos: "noun", sound: "usch aMIgusch" },
    "comigo": { pos: "pron", sound: "kuMIgu" },
    "visitar": { pos: "verb", verb: "visitar", sound: "wisiTAR" },
    "jantar fora": { pos: "verb", verb: "jantar", sound: "schãnTAR FOra" },
    "descansar": { pos: "verb", verb: "descansar", sound: "dschkãnßAR" },
    "talvez": { pos: "adv", sound: "talWESCH" },
    "combinado": { pos: "phrase", sound: "kõmbiNAdu" },
    "ir": { pos: "verb", verb: "ir" },
  },
  forms: {
    "engenheira": "o engenheiro",
    "euros": "o euro",
    "levanto": "levantar-se",
    "meus": "o meu",
  },
  names: ["Santa", "Maria", "André", "Beatriz", "Rita", "Helena"],
};
