import type { VerbDef } from "../types";

/**
 * Konjugationstabellen aller Verben des Kurses (Präsens + weitere Formen, die im
 * Kurs vorkommen). Welche Lektion ein Verb einführt, ergibt sich aus den
 * Vokabeln, die im Lexikon per `verb` darauf verweisen.
 */
export const verbList: VerbDef[] = [
  {
    inf: "desculpar",
    de: "entschuldigen",
    present: ["desculpo", "desculpas", "desculpa", "desculpamos", "desculpam"],
    presentDe: ["ich entschuldige", "du entschuldigst", "er/sie entschuldigt", "wir entschuldigen", "sie entschuldigen"],
    extra: [
      { label: "Imperativ (Sie)", forms: [["desculpe", "entschuldigen Sie / Entschuldigung"]] },
    ],
    note: "regelmäßig – „Desculpe“ ist die höfliche Aufforderung (Sie)",
    sound: "dschkulPAR",
  },
  {
    inf: "perceber",
    de: "verstehen",
    present: ["percebo", "percebes", "percebe", "percebemos", "percebem"],
    presentDe: ["ich verstehe", "du verstehst", "er/sie versteht", "wir verstehen", "sie verstehen"],
    note: "regelmäßig – in Portugal das übliche Wort für „verstehen“",
  },
  {
    inf: "ser",
    de: "sein",
    present: ["sou", "és", "é", "somos", "são"],
    presentDe: ["ich bin", "du bist", "er/sie ist", "wir sind", "sie sind"],
    extra: [
      { label: "Vergangenheit (Pretérito)", forms: [["foi", "war"]] },
    ],
    note: "unregelmäßig – für Herkunft, Beruf, Eigenschaften, Uhrzeit",
  },
  {
    inf: "chamar-se",
    de: "heißen",
    present: ["chamo-me", "chamas-te", "chama-se", "chamamo-nos", "chamam-se"],
    presentDe: ["ich heiße", "du heißt", "er/sie heißt", "wir heißen", "sie heißen"],
    extra: [
      { label: "Nach não / Fragewort", forms: [["te chamas", "du heißt"]] },
    ],
    note: "reflexiv: das me steht in Portugal hinter dem Verb, nach Fragewörtern davor",
  },
  {
    inf: "morar",
    de: "wohnen",
    present: ["moro", "moras", "mora", "moramos", "moram"],
    presentDe: ["ich wohne", "du wohnst", "er/sie wohnt", "wir wohnen", "sie wohnen"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "ter",
    de: "haben",
    present: ["tenho", "tens", "tem", "temos", "têm"],
    presentDe: ["ich habe", "du hast", "er/sie hat", "wir haben", "sie haben"],
    note: "unregelmäßig – auch für das Alter: „Tenho vinte anos“; eles têm mit Zirkumflex",
  },
  {
    inf: "querer",
    de: "wollen",
    present: ["quero", "queres", "quer", "queremos", "querem"],
    presentDe: ["ich will", "du willst", "er/sie will", "wir wollen", "sie wollen"],
    extra: [
      { label: "Höfliche Bitte (Imperfeito)", forms: [["queria", "ich hätte gern / ich möchte"]] },
    ],
    note: "unregelmäßig",
  },
  {
    inf: "fazer",
    de: "machen, tun",
    present: ["faço", "fazes", "faz", "fazemos", "fazem"],
    presentDe: ["ich mache", "du machst", "er/sie macht", "wir machen", "sie machen"],
    note: "unregelmäßig – „se faz favor“ heißt wörtlich „wenn Sie die Güte haben“",
    sound: "faSER",
  },
  {
    inf: "desejar",
    de: "wünschen",
    present: ["desejo", "desejas", "deseja", "desejamos", "desejam"],
    presentDe: ["ich wünsche", "du wünschst", "er/sie wünscht", "wir wünschen", "sie wünschen"],
    note: "regelmäßig – „O que deseja?“ = Was darf es sein?",
  },
  {
    inf: "comer",
    de: "essen",
    present: ["como", "comes", "come", "comemos", "comem"],
    presentDe: ["ich esse", "du isst", "er/sie isst", "wir essen", "sie essen"],
    note: "regelmäßig auf -er",
  },
  {
    inf: "beber",
    de: "trinken",
    present: ["bebo", "bebes", "bebe", "bebemos", "bebem"],
    presentDe: ["ich trinke", "du trinkst", "er/sie trinkt", "wir trinken", "sie trinken"],
    note: "regelmäßig auf -er",
  },
  {
    inf: "gostar",
    de: "mögen, gernhaben",
    present: ["gosto", "gostas", "gosta", "gostamos", "gostam"],
    presentDe: ["ich mag", "du magst", "er/sie mag", "wir mögen", "sie mögen"],
    note: "regelmäßig – immer mit de: „gosto de peixe“",
  },
  {
    inf: "estar",
    de: "sein (Zustand, Ort)",
    present: ["estou", "estás", "está", "estamos", "estão"],
    presentDe: ["ich bin", "du bist", "er/sie ist", "wir sind", "sie sind"],
    note: "unregelmäßig – für Befinden und Aufenthaltsort; estar a + Infinitiv = gerade etwas tun",
  },
  {
    inf: "trabalhar",
    de: "arbeiten",
    present: ["trabalho", "trabalhas", "trabalha", "trabalhamos", "trabalham"],
    presentDe: ["ich arbeite", "du arbeitest", "er/sie arbeitet", "wir arbeiten", "sie arbeiten"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "ficar",
    de: "liegen, sich befinden; bleiben",
    present: ["fico", "ficas", "fica", "ficamos", "ficam"],
    presentDe: ["ich liege", "du liegst", "er/sie liegt", "wir liegen", "sie liegen"],
    note: "regelmäßig – für die Lage von Orten: „Onde fica …?“",
  },
  {
    inf: "seguir",
    de: "folgen, weitergehen",
    present: ["sigo", "segues", "segue", "seguimos", "seguem"],
    presentDe: ["ich folge", "du folgst", "er/sie folgt", "wir folgen", "sie folgen"],
    extra: [
      { label: "Imperativ (Sie)", forms: [["siga", "gehen Sie (weiter)"]] },
    ],
    note: "unregelmäßig (eu sigo)",
    sound: "ßGIR",
  },
  {
    inf: "ir",
    de: "gehen, fahren",
    present: ["vou", "vais", "vai", "vamos", "vão"],
    presentDe: ["ich gehe", "du gehst", "er/sie geht", "wir gehen", "sie gehen"],
    note: "unregelmäßig – ir + Infinitiv drückt Pläne aus: „Vou jantar fora“",
  },
  {
    inf: "apanhar",
    de: "nehmen (Bus, Zug), erwischen",
    present: ["apanho", "apanhas", "apanha", "apanhamos", "apanham"],
    presentDe: ["ich nehme", "du nimmst", "er/sie nimmt", "wir nehmen", "sie nehmen"],
    note: "regelmäßig – in Portugal statt brasilianisch „pegar“",
  },
  {
    inf: "partir",
    de: "abfahren, abreisen",
    present: ["parto", "partes", "parte", "partimos", "partem"],
    presentDe: ["ich fahre ab", "du fährst ab", "er/sie fährt ab", "wir fahren ab", "sie fahren ab"],
    note: "regelmäßig auf -ir – „Quando parte o comboio?“",
  },
  {
    inf: "custar",
    de: "kosten",
    present: ["custo", "custas", "custa", "custamos", "custam"],
    presentDe: ["ich koste", "du kostest", "er/sie kostet", "wir kosten", "sie kosten"],
    note: "regelmäßig – meist nur 3. Person: custa / custam",
  },
  {
    inf: "pagar",
    de: "bezahlen",
    present: ["pago", "pagas", "paga", "pagamos", "pagam"],
    presentDe: ["ich bezahle", "du bezahlst", "er/sie bezahlt", "wir bezahlen", "sie bezahlen"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "poder",
    de: "können, dürfen",
    present: ["posso", "podes", "pode", "podemos", "podem"],
    presentDe: ["ich kann", "du kannst", "er/sie kann", "wir können", "sie können"],
    note: "unregelmäßig – mit Infinitiv: „Posso pagar?“, „Pode repetir?“",
  },
  {
    inf: "abrir",
    de: "öffnen, aufmachen",
    present: ["abro", "abres", "abre", "abrimos", "abrem"],
    presentDe: ["ich öffne", "du öffnest", "er/sie öffnet", "wir öffnen", "sie öffnen"],
    note: "regelmäßig auf -ir",
  },
  {
    inf: "chegar",
    de: "ankommen",
    present: ["chego", "chegas", "chega", "chegamos", "chegam"],
    presentDe: ["ich komme an", "du kommst an", "er/sie kommt an", "wir kommen an", "sie kommen an"],
    note: "regelmäßig – eu chego mit g",
    sound: "schGAR",
  },
  {
    inf: "falar",
    de: "sprechen",
    present: ["falo", "falas", "fala", "falamos", "falam"],
    presentDe: ["ich spreche", "du sprichst", "er/sie spricht", "wir sprechen", "sie sprechen"],
    note: "regelmäßig auf -ar – nach falar meist kein Artikel: „Falo português“",
  },
  {
    inf: "estudar",
    de: "lernen, studieren",
    present: ["estudo", "estudas", "estuda", "estudamos", "estudam"],
    presentDe: ["ich lerne", "du lernst", "er/sie lernt", "wir lernen", "sie lernen"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "dizer",
    de: "sagen",
    present: ["digo", "dizes", "diz", "dizemos", "dizem"],
    presentDe: ["ich sage", "du sagst", "er/sie sagt", "wir sagen", "sie sagen"],
    extra: [
      { label: "Unpersönlich (man)", forms: [["se diz", "sagt man"]] },
    ],
    note: "unregelmäßig (eu digo)",
    sound: "diSER",
  },
  {
    inf: "saber",
    de: "wissen",
    present: ["sei", "sabes", "sabe", "sabemos", "sabem"],
    presentDe: ["ich weiß", "du weißt", "er/sie weiß", "wir wissen", "sie wissen"],
    note: "unregelmäßig (eu sei) – „Sabe onde fica …?“ = Wissen Sie, wo …?",
  },
  {
    inf: "repetir",
    de: "wiederholen",
    present: ["repito", "repetes", "repete", "repetimos", "repetem"],
    presentDe: ["ich wiederhole", "du wiederholst", "er/sie wiederholt", "wir wiederholen", "sie wiederholen"],
    note: "unregelmäßig (eu repito) – „Pode repetir?“",
  },
  {
    inf: "acordar",
    de: "aufwachen",
    present: ["acordo", "acordas", "acorda", "acordamos", "acordam"],
    presentDe: ["ich wache auf", "du wachst auf", "er/sie wacht auf", "wir wachen auf", "sie wachen auf"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "levantar-se",
    de: "aufstehen",
    present: ["levanto-me", "levantas-te", "levanta-se", "levantamo-nos", "levantam-se"],
    presentDe: ["ich stehe auf", "du stehst auf", "er/sie steht auf", "wir stehen auf", "sie stehen auf"],
    extra: [
      { label: "Nach não / Fragewort", forms: [["me levanto", "ich stehe (nicht) auf"], ["te levantas", "du stehst auf"]] },
    ],
    note: "reflexiv: das me steht in Portugal hinter dem Verb, nach não und Fragewörtern davor",
  },
  {
    inf: "deitar-se",
    de: "ins Bett gehen, sich hinlegen",
    present: ["deito-me", "deitas-te", "deita-se", "deitamo-nos", "deitam-se"],
    presentDe: ["ich gehe ins Bett", "du gehst ins Bett", "er/sie geht ins Bett", "wir gehen ins Bett", "sie gehen ins Bett"],
    note: "reflexiv: das me steht in Portugal hinter dem Verb",
  },
  {
    inf: "tomar",
    de: "nehmen; trinken, essen",
    present: ["tomo", "tomas", "toma", "tomamos", "tomam"],
    presentDe: ["ich nehme", "du nimmst", "er/sie nimmt", "wir nehmen", "sie nehmen"],
    note: "regelmäßig – „tomar duche“ = duschen",
  },
  {
    inf: "sair",
    de: "hinausgehen, ausgehen, losgehen",
    present: ["saio", "sais", "sai", "saímos", "saem"],
    presentDe: ["ich gehe aus", "du gehst aus", "er/sie geht aus", "wir gehen aus", "sie gehen aus"],
    note: "unregelmäßig (eu saio)",
    sound: "ßaIR",
  },
  {
    inf: "visitar",
    de: "besuchen",
    present: ["visito", "visitas", "visita", "visitamos", "visitam"],
    presentDe: ["ich besuche", "du besuchst", "er/sie besucht", "wir besuchen", "sie besuchen"],
    note: "regelmäßig auf -ar",
  },
  {
    inf: "jantar",
    de: "zu Abend essen",
    present: ["janto", "jantas", "janta", "jantamos", "jantam"],
    presentDe: ["ich esse zu Abend", "du isst zu Abend", "er/sie isst zu Abend", "wir essen zu Abend", "sie essen zu Abend"],
    note: "regelmäßig – auch Nomen: o jantar = das Abendessen; „jantar fora“ = auswärts essen",
  },
  {
    inf: "descansar",
    de: "sich ausruhen",
    present: ["descanso", "descansas", "descansa", "descansamos", "descansam"],
    presentDe: ["ich ruhe mich aus", "du ruhst dich aus", "er/sie ruht sich aus", "wir ruhen uns aus", "sie ruhen sich aus"],
    note: "regelmäßig auf -ar",
  },
];
